// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file

import (
	fileApi "shop-goframe-micro-service-refacotor/app/gateway-admin/api/file"
)

type ControllerV1 struct{}

func NewV1() fileApi.IFileV1 {
	return &ControllerV1{}
}
