// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: rotation_info/v1/rotation_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/banner/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type RotationInfoCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PicUrl string `protobuf:"bytes,1,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"轮播图片"` // 轮播图片
	Link   string `protobuf:"bytes,2,opt,name=Link,proto3" json:"Link,omitempty" dc:"跳转链接"`     // 跳转链接
	Sort   uint32 `protobuf:"varint,3,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"排序字段"`    // 排序字段
}

func (x *RotationInfoCreateReq) Reset() {
	*x = RotationInfoCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoCreateReq) ProtoMessage() {}

func (x *RotationInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoCreateReq.ProtoReflect.Descriptor instead.
func (*RotationInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{0}
}

func (x *RotationInfoCreateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *RotationInfoCreateReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RotationInfoCreateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type RotationInfoCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RotationInfoCreateRes) Reset() {
	*x = RotationInfoCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoCreateRes) ProtoMessage() {}

func (x *RotationInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoCreateRes.ProtoReflect.Descriptor instead.
func (*RotationInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{1}
}

func (x *RotationInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RotationInfoUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                  //
	PicUrl string `protobuf:"bytes,2,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"轮播图片"` // 轮播图片
	Link   string `protobuf:"bytes,3,opt,name=Link,proto3" json:"Link,omitempty" dc:"跳转链接"`     // 跳转链接
	Sort   uint32 `protobuf:"varint,4,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"排序字段"`    // 排序字段
}

func (x *RotationInfoUpdateReq) Reset() {
	*x = RotationInfoUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoUpdateReq) ProtoMessage() {}

func (x *RotationInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*RotationInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{2}
}

func (x *RotationInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RotationInfoUpdateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *RotationInfoUpdateReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *RotationInfoUpdateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type RotationInfoUpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RotationInfoUpdateRes) Reset() {
	*x = RotationInfoUpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoUpdateRes) ProtoMessage() {}

func (x *RotationInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*RotationInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{3}
}

func (x *RotationInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RotationInfoDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RotationInfoDeleteReq) Reset() {
	*x = RotationInfoDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoDeleteReq) ProtoMessage() {}

func (x *RotationInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*RotationInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{4}
}

func (x *RotationInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RotationInfoDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RotationInfoDeleteRes) Reset() {
	*x = RotationInfoDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoDeleteRes) ProtoMessage() {}

func (x *RotationInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*RotationInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{5}
}

type RotationInfoGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sort uint32 `protobuf:"varint,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Page uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
}

func (x *RotationInfoGetListReq) Reset() {
	*x = RotationInfoGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoGetListReq) ProtoMessage() {}

func (x *RotationInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoGetListReq.ProtoReflect.Descriptor instead.
func (*RotationInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{6}
}

func (x *RotationInfoGetListReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *RotationInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RotationInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RotationInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*pbentity.RotationInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page  uint32                   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  uint32                   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total uint32                   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *RotationInfoListResponse) Reset() {
	*x = RotationInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoListResponse) ProtoMessage() {}

func (x *RotationInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoListResponse.ProtoReflect.Descriptor instead.
func (*RotationInfoListResponse) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{7}
}

func (x *RotationInfoListResponse) GetList() []*pbentity.RotationInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RotationInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RotationInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RotationInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RotationInfoGetListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *RotationInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RotationInfoGetListRes) Reset() {
	*x = RotationInfoGetListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RotationInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationInfoGetListRes) ProtoMessage() {}

func (x *RotationInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_rotation_info_v1_rotation_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationInfoGetListRes.ProtoReflect.Descriptor instead.
func (*RotationInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_rotation_info_v1_rotation_info_proto_rawDescGZIP(), []int{8}
}

func (x *RotationInfoGetListRes) GetData() *RotationInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rotation_info_v1_rotation_info_proto protoreflect.FileDescriptor

var file_rotation_info_v1_rotation_info_proto_rawDesc = []byte{
	0x0a, 0x24, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f,
	0x76, 0x31, 0x2f, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2f, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x15, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x22,
	0x27, 0x0a, 0x15, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x67, 0x0a, 0x15, 0x52, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6e,
	0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x6f, 0x72,
	0x74, 0x22, 0x27, 0x0a, 0x15, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x52, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x16,
	0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x18, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x58, 0x0a, 0x16, 0x52, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x8a, 0x03, 0x0a, 0x0d, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x5f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x28, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x72, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x27, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x72, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x27,
	0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x5c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x72,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x42, 0x46, 0x5a, 0x44, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x67, 0x6f, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x72,
	0x65, 0x66, 0x61, 0x63, 0x6f, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rotation_info_v1_rotation_info_proto_rawDescOnce sync.Once
	file_rotation_info_v1_rotation_info_proto_rawDescData = file_rotation_info_v1_rotation_info_proto_rawDesc
)

func file_rotation_info_v1_rotation_info_proto_rawDescGZIP() []byte {
	file_rotation_info_v1_rotation_info_proto_rawDescOnce.Do(func() {
		file_rotation_info_v1_rotation_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_rotation_info_v1_rotation_info_proto_rawDescData)
	})
	return file_rotation_info_v1_rotation_info_proto_rawDescData
}

var file_rotation_info_v1_rotation_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rotation_info_v1_rotation_info_proto_goTypes = []interface{}{
	(*RotationInfoCreateReq)(nil),    // 0: rotation_info.v1.RotationInfoCreateReq
	(*RotationInfoCreateRes)(nil),    // 1: rotation_info.v1.RotationInfoCreateRes
	(*RotationInfoUpdateReq)(nil),    // 2: rotation_info.v1.RotationInfoUpdateReq
	(*RotationInfoUpdateRes)(nil),    // 3: rotation_info.v1.RotationInfoUpdateRes
	(*RotationInfoDeleteReq)(nil),    // 4: rotation_info.v1.RotationInfoDeleteReq
	(*RotationInfoDeleteRes)(nil),    // 5: rotation_info.v1.RotationInfoDeleteRes
	(*RotationInfoGetListReq)(nil),   // 6: rotation_info.v1.RotationInfoGetListReq
	(*RotationInfoListResponse)(nil), // 7: rotation_info.v1.RotationInfoListResponse
	(*RotationInfoGetListRes)(nil),   // 8: rotation_info.v1.RotationInfoGetListRes
	(*pbentity.RotationInfo)(nil),    // 9: pbentity.RotationInfo
}
var file_rotation_info_v1_rotation_info_proto_depIdxs = []int32{
	9, // 0: rotation_info.v1.RotationInfoListResponse.list:type_name -> pbentity.RotationInfo
	7, // 1: rotation_info.v1.RotationInfoGetListRes.data:type_name -> rotation_info.v1.RotationInfoListResponse
	6, // 2: rotation_info.v1.rotation_info.GetList:input_type -> rotation_info.v1.RotationInfoGetListReq
	0, // 3: rotation_info.v1.rotation_info.Create:input_type -> rotation_info.v1.RotationInfoCreateReq
	2, // 4: rotation_info.v1.rotation_info.Update:input_type -> rotation_info.v1.RotationInfoUpdateReq
	4, // 5: rotation_info.v1.rotation_info.Delete:input_type -> rotation_info.v1.RotationInfoDeleteReq
	8, // 6: rotation_info.v1.rotation_info.GetList:output_type -> rotation_info.v1.RotationInfoGetListRes
	1, // 7: rotation_info.v1.rotation_info.Create:output_type -> rotation_info.v1.RotationInfoCreateRes
	3, // 8: rotation_info.v1.rotation_info.Update:output_type -> rotation_info.v1.RotationInfoUpdateRes
	5, // 9: rotation_info.v1.rotation_info.Delete:output_type -> rotation_info.v1.RotationInfoDeleteRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rotation_info_v1_rotation_info_proto_init() }
func file_rotation_info_v1_rotation_info_proto_init() {
	if File_rotation_info_v1_rotation_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rotation_info_v1_rotation_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_info_v1_rotation_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_info_v1_rotation_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_info_v1_rotation_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoUpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_info_v1_rotation_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_info_v1_rotation_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_info_v1_rotation_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_info_v1_rotation_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rotation_info_v1_rotation_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RotationInfoGetListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rotation_info_v1_rotation_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rotation_info_v1_rotation_info_proto_goTypes,
		DependencyIndexes: file_rotation_info_v1_rotation_info_proto_depIdxs,
		MessageInfos:      file_rotation_info_v1_rotation_info_proto_msgTypes,
	}.Build()
	File_rotation_info_v1_rotation_info_proto = out.File
	file_rotation_info_v1_rotation_info_proto_rawDesc = nil
	file_rotation_info_v1_rotation_info_proto_goTypes = nil
	file_rotation_info_v1_rotation_info_proto_depIdxs = nil
}
