// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package banner

import (
	position_info "shop-goframe-micro-service-refacotor/app/banner/api/position_info/v1"
	rotation_info "shop-goframe-micro-service-refacotor/app/banner/api/rotation_info/v1"

	"shop-goframe-micro-service-refacotor/app/gateway-h5/api/banner"
	"shop-goframe-micro-service-refacotor/utility/middleware"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	PositionInfoClient position_info.PositionInfoClient
	RotationInfoClient rotation_info.RotationInfoClient
}

func NewV1() banner.IBannerV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("banner", grpcx.Client.ChainUnary(
		middleware.GrpcClientTimeout,
	))
	return &ControllerV1{
		PositionInfoClient: position_info.NewPositionInfoClient(conn),
		RotationInfoClient: rotation_info.NewRotationInfoClient(conn),
	}
}
