// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoodsInfoClient is the client API for GoodsInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsInfoClient interface {
	// 商品列表
	GetList(ctx context.Context, in *GoodsInfoGetListReq, opts ...grpc.CallOption) (*GoodsInfoGetListRes, error)
	// 商品详情
	GetDetail(ctx context.Context, in *GoodsInfoGetDetailReq, opts ...grpc.CallOption) (*GoodsInfoGetDetailRes, error)
	// 创建商品
	Create(ctx context.Context, in *GoodsInfoCreateReq, opts ...grpc.CallOption) (*GoodsInfoCreateRes, error)
	// 修改商品
	Update(ctx context.Context, in *GoodsInfoUpdateReq, opts ...grpc.CallOption) (*GoodsInfoUpdateRes, error)
	// 删除商品
	Delete(ctx context.Context, in *GoodsInfoDeleteReq, opts ...grpc.CallOption) (*GoodsInfoDeleteRes, error)
}

type goodsInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsInfoClient(cc grpc.ClientConnInterface) GoodsInfoClient {
	return &goodsInfoClient{cc}
}

func (c *goodsInfoClient) GetList(ctx context.Context, in *GoodsInfoGetListReq, opts ...grpc.CallOption) (*GoodsInfoGetListRes, error) {
	out := new(GoodsInfoGetListRes)
	err := c.cc.Invoke(ctx, "/goods_info.v1.goods_info/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsInfoClient) GetDetail(ctx context.Context, in *GoodsInfoGetDetailReq, opts ...grpc.CallOption) (*GoodsInfoGetDetailRes, error) {
	out := new(GoodsInfoGetDetailRes)
	err := c.cc.Invoke(ctx, "/goods_info.v1.goods_info/GetDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsInfoClient) Create(ctx context.Context, in *GoodsInfoCreateReq, opts ...grpc.CallOption) (*GoodsInfoCreateRes, error) {
	out := new(GoodsInfoCreateRes)
	err := c.cc.Invoke(ctx, "/goods_info.v1.goods_info/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsInfoClient) Update(ctx context.Context, in *GoodsInfoUpdateReq, opts ...grpc.CallOption) (*GoodsInfoUpdateRes, error) {
	out := new(GoodsInfoUpdateRes)
	err := c.cc.Invoke(ctx, "/goods_info.v1.goods_info/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsInfoClient) Delete(ctx context.Context, in *GoodsInfoDeleteReq, opts ...grpc.CallOption) (*GoodsInfoDeleteRes, error) {
	out := new(GoodsInfoDeleteRes)
	err := c.cc.Invoke(ctx, "/goods_info.v1.goods_info/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsInfoServer is the server API for GoodsInfo service.
// All implementations must embed UnimplementedGoodsInfoServer
// for forward compatibility
type GoodsInfoServer interface {
	// 商品列表
	GetList(context.Context, *GoodsInfoGetListReq) (*GoodsInfoGetListRes, error)
	// 商品详情
	GetDetail(context.Context, *GoodsInfoGetDetailReq) (*GoodsInfoGetDetailRes, error)
	// 创建商品
	Create(context.Context, *GoodsInfoCreateReq) (*GoodsInfoCreateRes, error)
	// 修改商品
	Update(context.Context, *GoodsInfoUpdateReq) (*GoodsInfoUpdateRes, error)
	// 删除商品
	Delete(context.Context, *GoodsInfoDeleteReq) (*GoodsInfoDeleteRes, error)
	mustEmbedUnimplementedGoodsInfoServer()
}

// UnimplementedGoodsInfoServer must be embedded to have forward compatible implementations.
type UnimplementedGoodsInfoServer struct {
}

func (UnimplementedGoodsInfoServer) GetList(context.Context, *GoodsInfoGetListReq) (*GoodsInfoGetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedGoodsInfoServer) GetDetail(context.Context, *GoodsInfoGetDetailReq) (*GoodsInfoGetDetailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedGoodsInfoServer) Create(context.Context, *GoodsInfoCreateReq) (*GoodsInfoCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGoodsInfoServer) Update(context.Context, *GoodsInfoUpdateReq) (*GoodsInfoUpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedGoodsInfoServer) Delete(context.Context, *GoodsInfoDeleteReq) (*GoodsInfoDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGoodsInfoServer) mustEmbedUnimplementedGoodsInfoServer() {}

// UnsafeGoodsInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsInfoServer will
// result in compilation errors.
type UnsafeGoodsInfoServer interface {
	mustEmbedUnimplementedGoodsInfoServer()
}

func RegisterGoodsInfoServer(s grpc.ServiceRegistrar, srv GoodsInfoServer) {
	s.RegisterService(&GoodsInfo_ServiceDesc, srv)
}

func _GoodsInfo_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsInfoGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods_info.v1.goods_info/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).GetList(ctx, req.(*GoodsInfoGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsInfo_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsInfoGetDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods_info.v1.goods_info/GetDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).GetDetail(ctx, req.(*GoodsInfoGetDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsInfo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsInfoCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods_info.v1.goods_info/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).Create(ctx, req.(*GoodsInfoCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsInfo_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsInfoUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods_info.v1.goods_info/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).Update(ctx, req.(*GoodsInfoUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsInfo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsInfoDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsInfoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods_info.v1.goods_info/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsInfoServer).Delete(ctx, req.(*GoodsInfoDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsInfo_ServiceDesc is the grpc.ServiceDesc for GoodsInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goods_info.v1.goods_info",
	HandlerType: (*GoodsInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _GoodsInfo_GetList_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _GoodsInfo_GetDetail_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _GoodsInfo_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _GoodsInfo_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GoodsInfo_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods_info/v1/goods_info.proto",
}
