// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: goods_info/v1/goods_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/goods/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsInfoGetDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GoodsInfoGetDetailReq) Reset() {
	*x = GoodsInfoGetDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoGetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetDetailReq) ProtoMessage() {}

func (x *GoodsInfoGetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetDetailReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetDetailReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsInfoGetDetailReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoGetDetailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *pbentity.GoodsInfo `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GoodsInfoGetDetailRes) Reset() {
	*x = GoodsInfoGetDetailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoGetDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetDetailRes) ProtoMessage() {}

func (x *GoodsInfoGetDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetDetailRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetDetailRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsInfoGetDetailRes) GetData() *pbentity.GoodsInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 新增消息定义
type GoodsInfoCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price            uint64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Images           string `protobuf:"bytes,3,opt,name=Images,proto3" json:"Images,omitempty" dc:"支持单图,多图"` // 支持单图,多图
	Level1CategoryId uint32 `protobuf:"varint,4,opt,name=level1_category_id,json=level1CategoryId,proto3" json:"level1_category_id,omitempty"`
	Level2CategoryId uint32 `protobuf:"varint,5,opt,name=level2_category_id,json=level2CategoryId,proto3" json:"level2_category_id,omitempty"`
	Level3CategoryId uint32 `protobuf:"varint,6,opt,name=level3_category_id,json=level3CategoryId,proto3" json:"level3_category_id,omitempty"`
	Brand            string `protobuf:"bytes,7,opt,name=brand,proto3" json:"brand,omitempty"`
	Stock            uint32 `protobuf:"varint,8,opt,name=stock,proto3" json:"stock,omitempty"`
	Sale             uint32 `protobuf:"varint,9,opt,name=sale,proto3" json:"sale,omitempty"`
	Tags             string `protobuf:"bytes,10,opt,name=tags,proto3" json:"tags,omitempty"`
	DetailInfo       string `protobuf:"bytes,11,opt,name=detail_info,json=detailInfo,proto3" json:"detail_info,omitempty"`
}

func (x *GoodsInfoCreateReq) Reset() {
	*x = GoodsInfoCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoCreateReq) ProtoMessage() {}

func (x *GoodsInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoCreateReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsInfoCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetLevel1CategoryId() uint32 {
	if x != nil {
		return x.Level1CategoryId
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetLevel2CategoryId() uint32 {
	if x != nil {
		return x.Level2CategoryId
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetLevel3CategoryId() uint32 {
	if x != nil {
		return x.Level3CategoryId
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetSale() uint32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsInfoCreateReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GoodsInfoCreateReq) GetDetailInfo() string {
	if x != nil {
		return x.DetailInfo
	}
	return ""
}

type GoodsInfoCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GoodsInfoCreateRes) Reset() {
	*x = GoodsInfoCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoCreateRes) ProtoMessage() {}

func (x *GoodsInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoCreateRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{3}
}

func (x *GoodsInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                                         //
	Name             string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" dc:"商品名字"`                            // 商品名字
	Images           string `protobuf:"bytes,3,opt,name=Images,proto3" json:"Images,omitempty" dc:"支持单图,多图"`                     // 支持单图,多图
	Price            int32  `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty" dc:"价格(分)"`                        // 价格(分)
	Level1CategoryId int32  `protobuf:"varint,5,opt,name=Level1CategoryId,proto3" json:"Level1CategoryId,omitempty" dc:"1级分类id"` // 1级分类id
	Level2CategoryId int32  `protobuf:"varint,6,opt,name=Level2CategoryId,proto3" json:"Level2CategoryId,omitempty" dc:"2级分类id"` // 2级分类id
	Level3CategoryId int32  `protobuf:"varint,7,opt,name=Level3CategoryId,proto3" json:"Level3CategoryId,omitempty" dc:"3级分类id"` // 3级分类id
	Brand            string `protobuf:"bytes,8,opt,name=Brand,proto3" json:"Brand,omitempty" dc:"品牌"`                            // 品牌
	Stock            int32  `protobuf:"varint,9,opt,name=Stock,proto3" json:"Stock,omitempty" dc:"库存"`                           // 库存
	Sale             int32  `protobuf:"varint,10,opt,name=Sale,proto3" json:"Sale,omitempty" dc:"销量"`                            // 销量
	Tags             string `protobuf:"bytes,11,opt,name=Tags,proto3" json:"Tags,omitempty" dc:"标签"`                             // 标签
	DetailInfo       string `protobuf:"bytes,12,opt,name=DetailInfo,proto3" json:"DetailInfo,omitempty" dc:"商品详情"`               // 商品详情
}

func (x *GoodsInfoUpdateReq) Reset() {
	*x = GoodsInfoUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoUpdateReq) ProtoMessage() {}

func (x *GoodsInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetLevel1CategoryId() int32 {
	if x != nil {
		return x.Level1CategoryId
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetLevel2CategoryId() int32 {
	if x != nil {
		return x.Level2CategoryId
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetLevel3CategoryId() int32 {
	if x != nil {
		return x.Level3CategoryId
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetSale() int32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

func (x *GoodsInfoUpdateReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *GoodsInfoUpdateReq) GetDetailInfo() string {
	if x != nil {
		return x.DetailInfo
	}
	return ""
}

type GoodsInfoUpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GoodsInfoUpdateRes) Reset() {
	*x = GoodsInfoUpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoUpdateRes) ProtoMessage() {}

func (x *GoodsInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GoodsInfoDeleteReq) Reset() {
	*x = GoodsInfoDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoDeleteReq) ProtoMessage() {}

func (x *GoodsInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsInfoDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GoodsInfoDeleteRes) Reset() {
	*x = GoodsInfoDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoDeleteRes) ProtoMessage() {}

func (x *GoodsInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{7}
}

type GoodsInfoGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
}

func (x *GoodsInfoGetListReq) Reset() {
	*x = GoodsInfoGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetListReq) ProtoMessage() {}

func (x *GoodsInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetListReq.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{8}
}

func (x *GoodsInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GoodsInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*pbentity.GoodsInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page  uint32                `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  uint32                `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total uint32                `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GoodsInfoListResponse) Reset() {
	*x = GoodsInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoListResponse) ProtoMessage() {}

func (x *GoodsInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoListResponse.ProtoReflect.Descriptor instead.
func (*GoodsInfoListResponse) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{9}
}

func (x *GoodsInfoListResponse) GetList() []*pbentity.GoodsInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GoodsInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GoodsInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GoodsInfoGetListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *GoodsInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GoodsInfoGetListRes) Reset() {
	*x = GoodsInfoGetListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_info_v1_goods_info_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoGetListRes) ProtoMessage() {}

func (x *GoodsInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_info_v1_goods_info_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoGetListRes.ProtoReflect.Descriptor instead.
func (*GoodsInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_goods_info_v1_goods_info_proto_rawDescGZIP(), []int{10}
}

func (x *GoodsInfoGetListRes) GetData() *GoodsInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_goods_info_v1_goods_info_proto protoreflect.FileDescriptor

var file_goods_info_v1_goods_info_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31, 0x2f,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x1a,
	0x19, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x15, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xd5, 0x02, 0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2c,
	0x0a, 0x12, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x31, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x31, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x32, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x32,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x33, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x33, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x74, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x24, 0x0a,
	0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x22, 0xde, 0x02, 0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x10,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x31, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x31, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x32, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x32, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x33, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x33, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x61, 0x6c, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x61, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x61, 0x67, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x61, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x3d, 0x0a, 0x13, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x7e, 0x0a, 0x15, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x4f, 0x0a, 0x13, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xb2, 0x03, 0x0a, 0x0a, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x53, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x22, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x24, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x73,
	0x68, 0x6f, 0x70, 0x2d, 0x67, 0x6f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2d, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goods_info_v1_goods_info_proto_rawDescOnce sync.Once
	file_goods_info_v1_goods_info_proto_rawDescData = file_goods_info_v1_goods_info_proto_rawDesc
)

func file_goods_info_v1_goods_info_proto_rawDescGZIP() []byte {
	file_goods_info_v1_goods_info_proto_rawDescOnce.Do(func() {
		file_goods_info_v1_goods_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_info_v1_goods_info_proto_rawDescData)
	})
	return file_goods_info_v1_goods_info_proto_rawDescData
}

var file_goods_info_v1_goods_info_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_goods_info_v1_goods_info_proto_goTypes = []interface{}{
	(*GoodsInfoGetDetailReq)(nil), // 0: goods_info.v1.GoodsInfoGetDetailReq
	(*GoodsInfoGetDetailRes)(nil), // 1: goods_info.v1.GoodsInfoGetDetailRes
	(*GoodsInfoCreateReq)(nil),    // 2: goods_info.v1.GoodsInfoCreateReq
	(*GoodsInfoCreateRes)(nil),    // 3: goods_info.v1.GoodsInfoCreateRes
	(*GoodsInfoUpdateReq)(nil),    // 4: goods_info.v1.GoodsInfoUpdateReq
	(*GoodsInfoUpdateRes)(nil),    // 5: goods_info.v1.GoodsInfoUpdateRes
	(*GoodsInfoDeleteReq)(nil),    // 6: goods_info.v1.GoodsInfoDeleteReq
	(*GoodsInfoDeleteRes)(nil),    // 7: goods_info.v1.GoodsInfoDeleteRes
	(*GoodsInfoGetListReq)(nil),   // 8: goods_info.v1.GoodsInfoGetListReq
	(*GoodsInfoListResponse)(nil), // 9: goods_info.v1.GoodsInfoListResponse
	(*GoodsInfoGetListRes)(nil),   // 10: goods_info.v1.GoodsInfoGetListRes
	(*pbentity.GoodsInfo)(nil),    // 11: pbentity.GoodsInfo
}
var file_goods_info_v1_goods_info_proto_depIdxs = []int32{
	11, // 0: goods_info.v1.GoodsInfoGetDetailRes.data:type_name -> pbentity.GoodsInfo
	11, // 1: goods_info.v1.GoodsInfoListResponse.list:type_name -> pbentity.GoodsInfo
	9,  // 2: goods_info.v1.GoodsInfoGetListRes.data:type_name -> goods_info.v1.GoodsInfoListResponse
	8,  // 3: goods_info.v1.goods_info.GetList:input_type -> goods_info.v1.GoodsInfoGetListReq
	0,  // 4: goods_info.v1.goods_info.GetDetail:input_type -> goods_info.v1.GoodsInfoGetDetailReq
	2,  // 5: goods_info.v1.goods_info.Create:input_type -> goods_info.v1.GoodsInfoCreateReq
	4,  // 6: goods_info.v1.goods_info.Update:input_type -> goods_info.v1.GoodsInfoUpdateReq
	6,  // 7: goods_info.v1.goods_info.Delete:input_type -> goods_info.v1.GoodsInfoDeleteReq
	10, // 8: goods_info.v1.goods_info.GetList:output_type -> goods_info.v1.GoodsInfoGetListRes
	1,  // 9: goods_info.v1.goods_info.GetDetail:output_type -> goods_info.v1.GoodsInfoGetDetailRes
	3,  // 10: goods_info.v1.goods_info.Create:output_type -> goods_info.v1.GoodsInfoCreateRes
	5,  // 11: goods_info.v1.goods_info.Update:output_type -> goods_info.v1.GoodsInfoUpdateRes
	7,  // 12: goods_info.v1.goods_info.Delete:output_type -> goods_info.v1.GoodsInfoDeleteRes
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_goods_info_v1_goods_info_proto_init() }
func file_goods_info_v1_goods_info_proto_init() {
	if File_goods_info_v1_goods_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goods_info_v1_goods_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoGetDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoGetDetailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoUpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_info_v1_goods_info_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsInfoGetListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_info_v1_goods_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_info_v1_goods_info_proto_goTypes,
		DependencyIndexes: file_goods_info_v1_goods_info_proto_depIdxs,
		MessageInfos:      file_goods_info_v1_goods_info_proto_msgTypes,
	}.Build()
	File_goods_info_v1_goods_info_proto = out.File
	file_goods_info_v1_goods_info_proto_rawDesc = nil
	file_goods_info_v1_goods_info_proto_goTypes = nil
	file_goods_info_v1_goods_info_proto_depIdxs = nil
}
