// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: refund_info/v1/refund_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/order/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type RefundInfoCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty" dc:"用户id"`       // 用户id
	OrderId uint32 `protobuf:"varint,2,opt,name=OrderId,proto3" json:"OrderId,omitempty" dc:"订单id"`     // 订单id
	GoodsId uint32 `protobuf:"varint,3,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"要售后的商品id"` // 要售后的商品id
	Reason  string `protobuf:"bytes,4,opt,name=Reason,proto3" json:"Reason,omitempty" dc:"退款原因"`        // 退款原因
}

func (x *RefundInfoCreateReq) Reset() {
	*x = RefundInfoCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoCreateReq) ProtoMessage() {}

func (x *RefundInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoCreateReq.ProtoReflect.Descriptor instead.
func (*RefundInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{0}
}

func (x *RefundInfoCreateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RefundInfoCreateReq) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RefundInfoCreateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *RefundInfoCreateReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundInfoCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RefundInfoCreateRes) Reset() {
	*x = RefundInfoCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoCreateRes) ProtoMessage() {}

func (x *RefundInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoCreateRes.ProtoReflect.Descriptor instead.
func (*RefundInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{1}
}

func (x *RefundInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RefundInfoGetDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RefundInfoGetDetailReq) Reset() {
	*x = RefundInfoGetDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundInfoGetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoGetDetailReq) ProtoMessage() {}

func (x *RefundInfoGetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoGetDetailReq.ProtoReflect.Descriptor instead.
func (*RefundInfoGetDetailReq) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{2}
}

func (x *RefundInfoGetDetailReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RefundInfoGetDetailRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *pbentity.RefundInfo `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RefundInfoGetDetailRes) Reset() {
	*x = RefundInfoGetDetailRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundInfoGetDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoGetDetailRes) ProtoMessage() {}

func (x *RefundInfoGetDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoGetDetailRes.ProtoReflect.Descriptor instead.
func (*RefundInfoGetDetailRes) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{3}
}

func (x *RefundInfoGetDetailRes) GetData() *pbentity.RefundInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type RefundInfoGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
}

func (x *RefundInfoGetListReq) Reset() {
	*x = RefundInfoGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoGetListReq) ProtoMessage() {}

func (x *RefundInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoGetListReq.ProtoReflect.Descriptor instead.
func (*RefundInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{4}
}

func (x *RefundInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RefundInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RefundInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*pbentity.RefundInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page  uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *RefundInfoListResponse) Reset() {
	*x = RefundInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoListResponse) ProtoMessage() {}

func (x *RefundInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoListResponse.ProtoReflect.Descriptor instead.
func (*RefundInfoListResponse) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{5}
}

func (x *RefundInfoListResponse) GetList() []*pbentity.RefundInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RefundInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RefundInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RefundInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RefundInfoGetListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *RefundInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RefundInfoGetListRes) Reset() {
	*x = RefundInfoGetListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundInfoGetListRes) ProtoMessage() {}

func (x *RefundInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundInfoGetListRes.ProtoReflect.Descriptor instead.
func (*RefundInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{6}
}

func (x *RefundInfoGetListRes) GetData() *RefundInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 回调请求体
type RefundNotifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawBody string            `protobuf:"bytes,1,opt,name=raw_body,json=rawBody,proto3" json:"raw_body,omitempty" dc:"微信原始回调 body（JSON）"`                                                                                                                                                       // 微信原始回调 body（JSON）
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" dc:"回调的 HTTP headers (Wechatpay-Signature, Wechatpay-Timestamp, Wechatpay-Nonce, Wechatpay-Serial)"` // 回调的 HTTP headers (Wechatpay-Signature, Wechatpay-Timestamp, Wechatpay-Nonce, Wechatpay-Serial)
}

func (x *RefundNotifyReq) Reset() {
	*x = RefundNotifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundNotifyReq) ProtoMessage() {}

func (x *RefundNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundNotifyReq.ProtoReflect.Descriptor instead.
func (*RefundNotifyReq) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{7}
}

func (x *RefundNotifyReq) GetRawBody() string {
	if x != nil {
		return x.RawBody
	}
	return ""
}

func (x *RefundNotifyReq) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// 回调响应体
type RefundNotifyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefundNotifyRes) Reset() {
	*x = RefundNotifyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_refund_info_v1_refund_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefundNotifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundNotifyRes) ProtoMessage() {}

func (x *RefundNotifyRes) ProtoReflect() protoreflect.Message {
	mi := &file_refund_info_v1_refund_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundNotifyRes.ProtoReflect.Descriptor instead.
func (*RefundNotifyRes) Descriptor() ([]byte, []int) {
	return file_refund_info_v1_refund_info_proto_rawDescGZIP(), []int{8}
}

var File_refund_info_v1_refund_info_proto protoreflect.FileDescriptor

var file_refund_info_v1_refund_info_proto_rawDesc = []byte{
	0x0a, 0x20, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x76, 0x31, 0x1a, 0x1a, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x72, 0x65, 0x66,
	0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79,
	0x0a, 0x13, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x66,
	0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x28, 0x0a, 0x16, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x16, 0x52, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e,
	0x0a, 0x14, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x80,
	0x01, 0x0a, 0x16, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x52, 0x0a, 0x14, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb0, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77,
	0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x46, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x3a, 0x0a, 0x0c,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x32, 0xef, 0x02, 0x0a, 0x0b,
	0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x57, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x72,
	0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x26, 0x2e, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x72, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e,
	0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x23, 0x2e, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0c, 0x52, 0x65, 0x66,
	0x75, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1f, 0x2e, 0x72, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75, 0x6e,
	0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x72, 0x65, 0x66,
	0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x75,
	0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x43, 0x5a,
	0x41, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x67, 0x6f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2d, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x72, 0x65, 0x66, 0x61,
	0x63, 0x6f, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_refund_info_v1_refund_info_proto_rawDescOnce sync.Once
	file_refund_info_v1_refund_info_proto_rawDescData = file_refund_info_v1_refund_info_proto_rawDesc
)

func file_refund_info_v1_refund_info_proto_rawDescGZIP() []byte {
	file_refund_info_v1_refund_info_proto_rawDescOnce.Do(func() {
		file_refund_info_v1_refund_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_refund_info_v1_refund_info_proto_rawDescData)
	})
	return file_refund_info_v1_refund_info_proto_rawDescData
}

var file_refund_info_v1_refund_info_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_refund_info_v1_refund_info_proto_goTypes = []interface{}{
	(*RefundInfoCreateReq)(nil),    // 0: refund_info.v1.RefundInfoCreateReq
	(*RefundInfoCreateRes)(nil),    // 1: refund_info.v1.RefundInfoCreateRes
	(*RefundInfoGetDetailReq)(nil), // 2: refund_info.v1.RefundInfoGetDetailReq
	(*RefundInfoGetDetailRes)(nil), // 3: refund_info.v1.RefundInfoGetDetailRes
	(*RefundInfoGetListReq)(nil),   // 4: refund_info.v1.RefundInfoGetListReq
	(*RefundInfoListResponse)(nil), // 5: refund_info.v1.RefundInfoListResponse
	(*RefundInfoGetListRes)(nil),   // 6: refund_info.v1.RefundInfoGetListRes
	(*RefundNotifyReq)(nil),        // 7: refund_info.v1.RefundNotifyReq
	(*RefundNotifyRes)(nil),        // 8: refund_info.v1.RefundNotifyRes
	nil,                            // 9: refund_info.v1.RefundNotifyReq.HeadersEntry
	(*pbentity.RefundInfo)(nil),    // 10: pbentity.RefundInfo
}
var file_refund_info_v1_refund_info_proto_depIdxs = []int32{
	10, // 0: refund_info.v1.RefundInfoGetDetailRes.data:type_name -> pbentity.RefundInfo
	10, // 1: refund_info.v1.RefundInfoListResponse.list:type_name -> pbentity.RefundInfo
	5,  // 2: refund_info.v1.RefundInfoGetListRes.data:type_name -> refund_info.v1.RefundInfoListResponse
	9,  // 3: refund_info.v1.RefundNotifyReq.headers:type_name -> refund_info.v1.RefundNotifyReq.HeadersEntry
	4,  // 4: refund_info.v1.refund_info.GetList:input_type -> refund_info.v1.RefundInfoGetListReq
	2,  // 5: refund_info.v1.refund_info.GetDetail:input_type -> refund_info.v1.RefundInfoGetDetailReq
	0,  // 6: refund_info.v1.refund_info.Create:input_type -> refund_info.v1.RefundInfoCreateReq
	7,  // 7: refund_info.v1.refund_info.RefundNotify:input_type -> refund_info.v1.RefundNotifyReq
	6,  // 8: refund_info.v1.refund_info.GetList:output_type -> refund_info.v1.RefundInfoGetListRes
	3,  // 9: refund_info.v1.refund_info.GetDetail:output_type -> refund_info.v1.RefundInfoGetDetailRes
	1,  // 10: refund_info.v1.refund_info.Create:output_type -> refund_info.v1.RefundInfoCreateRes
	8,  // 11: refund_info.v1.refund_info.RefundNotify:output_type -> refund_info.v1.RefundNotifyRes
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_refund_info_v1_refund_info_proto_init() }
func file_refund_info_v1_refund_info_proto_init() {
	if File_refund_info_v1_refund_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_refund_info_v1_refund_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundInfoCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refund_info_v1_refund_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundInfoCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refund_info_v1_refund_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundInfoGetDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refund_info_v1_refund_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundInfoGetDetailRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refund_info_v1_refund_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundInfoGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refund_info_v1_refund_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refund_info_v1_refund_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundInfoGetListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refund_info_v1_refund_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundNotifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_refund_info_v1_refund_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefundNotifyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_refund_info_v1_refund_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_refund_info_v1_refund_info_proto_goTypes,
		DependencyIndexes: file_refund_info_v1_refund_info_proto_depIdxs,
		MessageInfos:      file_refund_info_v1_refund_info_proto_msgTypes,
	}.Build()
	File_refund_info_v1_refund_info_proto = out.File
	file_refund_info_v1_refund_info_proto_rawDesc = nil
	file_refund_info_v1_refund_info_proto_goTypes = nil
	file_refund_info_v1_refund_info_proto_depIdxs = nil
}
