// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"shop-goframe-micro-service-refacotor/app/flash-sale/internal/dao/internal"
)

// flashSaleOrderDao is the data access object for the table flash_sale_order.
// You can define custom methods on it to extend its functionality as needed.
type flashSaleOrderDao struct {
	*internal.FlashSaleOrderDao
}

var (
	// FlashSaleOrder is a globally accessible object for table flash_sale_order operations.
	FlashSaleOrder = flashSaleOrderDao{internal.NewFlashSaleOrderDao()}
)

// Add your custom methods and functionality below.
