// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"shop-goframe-micro-service-refacotor/app/flash-sale/internal/dao/internal"
)

// flashSaleGoodsDao is the data access object for the table flash_sale_goods.
// You can define custom methods on it to extend its functionality as needed.
type flashSaleGoodsDao struct {
	*internal.FlashSaleGoodsDao
}

var (
	// FlashSaleGoods is a globally accessible object for table flash_sale_goods operations.
	FlashSaleGoods = flashSaleGoodsDao{internal.NewFlashSaleGoodsDao()}
)

// Add your custom methods and functionality below.
