// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: praise_info/v1/praise_info.proto

package v1

import (
	pbentity "interaction/api/pbentity"
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type PraiseInfoCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId uint32 `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty" dc:"对象id"` // 对象id
	Type     uint32 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty" dc:"收藏类型：1商品 2文章"` // 收藏类型：1商品 2文章
}

func (x *PraiseInfoCreateReq) Reset() {
	*x = PraiseInfoCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_praise_info_v1_praise_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PraiseInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoCreateReq) ProtoMessage() {}

func (x *PraiseInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoCreateReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{0}
}

func (x *PraiseInfoCreateReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *PraiseInfoCreateReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type PraiseInfoCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PraiseInfoCreateRes) Reset() {
	*x = PraiseInfoCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_praise_info_v1_praise_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PraiseInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoCreateRes) ProtoMessage() {}

func (x *PraiseInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoCreateRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{1}
}

func (x *PraiseInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PraiseInfoDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                       //
	Type     uint32 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty" dc:"收藏类型：1商品 2文章"` // 收藏类型：1商品 2文章
	ObjectId uint32 `protobuf:"varint,3,opt,name=ObjectId,proto3" json:"ObjectId,omitempty" dc:"对象id"` // 对象id
}

func (x *PraiseInfoDeleteReq) Reset() {
	*x = PraiseInfoDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_praise_info_v1_praise_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PraiseInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoDeleteReq) ProtoMessage() {}

func (x *PraiseInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{2}
}

func (x *PraiseInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PraiseInfoDeleteReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PraiseInfoDeleteReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type PraiseInfoDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PraiseInfoDeleteRes) Reset() {
	*x = PraiseInfoDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_praise_info_v1_praise_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PraiseInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoDeleteRes) ProtoMessage() {}

func (x *PraiseInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{3}
}

func (x *PraiseInfoDeleteRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PraiseInfoGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty" dc:"收藏类型：1商品 2文章"` // 收藏类型：1商品 2文章
	Page uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
}

func (x *PraiseInfoGetListReq) Reset() {
	*x = PraiseInfoGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_praise_info_v1_praise_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PraiseInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoGetListReq) ProtoMessage() {}

func (x *PraiseInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoGetListReq.ProtoReflect.Descriptor instead.
func (*PraiseInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{4}
}

func (x *PraiseInfoGetListReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PraiseInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PraiseInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PraiseInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*pbentity.PraiseInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page  uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *PraiseInfoListResponse) Reset() {
	*x = PraiseInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_praise_info_v1_praise_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PraiseInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoListResponse) ProtoMessage() {}

func (x *PraiseInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoListResponse.ProtoReflect.Descriptor instead.
func (*PraiseInfoListResponse) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{5}
}

func (x *PraiseInfoListResponse) GetList() []*pbentity.PraiseInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PraiseInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PraiseInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PraiseInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PraiseInfoGetListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *PraiseInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PraiseInfoGetListRes) Reset() {
	*x = PraiseInfoGetListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_praise_info_v1_praise_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PraiseInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PraiseInfoGetListRes) ProtoMessage() {}

func (x *PraiseInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_praise_info_v1_praise_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PraiseInfoGetListRes.ProtoReflect.Descriptor instead.
func (*PraiseInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_praise_info_v1_praise_info_proto_rawDescGZIP(), []int{6}
}

func (x *PraiseInfoGetListRes) GetData() *PraiseInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_praise_info_v1_praise_info_proto protoreflect.FileDescriptor

var file_praise_info_v1_praise_info_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x76, 0x31, 0x1a, 0x1a, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x70, 0x72, 0x61,
	0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45,
	0x0a, 0x13, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x13,
	0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x14, 0x50, 0x72,
	0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x80,
	0x01, 0x0a, 0x16, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x52, 0x0a, 0x14, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x92, 0x02, 0x0a, 0x0b, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x57, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x24, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x54,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73,
	0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e,
	0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x23,
	0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x61, 0x69, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x49, 0x5a, 0x47, 0x73, 0x68,
	0x6f, 0x70, 0x2d, 0x67, 0x6f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x72, 0x65, 0x66, 0x61, 0x63, 0x6f, 0x74,
	0x6f, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x61, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_praise_info_v1_praise_info_proto_rawDescOnce sync.Once
	file_praise_info_v1_praise_info_proto_rawDescData = file_praise_info_v1_praise_info_proto_rawDesc
)

func file_praise_info_v1_praise_info_proto_rawDescGZIP() []byte {
	file_praise_info_v1_praise_info_proto_rawDescOnce.Do(func() {
		file_praise_info_v1_praise_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_praise_info_v1_praise_info_proto_rawDescData)
	})
	return file_praise_info_v1_praise_info_proto_rawDescData
}

var file_praise_info_v1_praise_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_praise_info_v1_praise_info_proto_goTypes = []interface{}{
	(*PraiseInfoCreateReq)(nil),    // 0: praise_info.v1.PraiseInfoCreateReq
	(*PraiseInfoCreateRes)(nil),    // 1: praise_info.v1.PraiseInfoCreateRes
	(*PraiseInfoDeleteReq)(nil),    // 2: praise_info.v1.PraiseInfoDeleteReq
	(*PraiseInfoDeleteRes)(nil),    // 3: praise_info.v1.PraiseInfoDeleteRes
	(*PraiseInfoGetListReq)(nil),   // 4: praise_info.v1.PraiseInfoGetListReq
	(*PraiseInfoListResponse)(nil), // 5: praise_info.v1.PraiseInfoListResponse
	(*PraiseInfoGetListRes)(nil),   // 6: praise_info.v1.PraiseInfoGetListRes
	(*pbentity.PraiseInfo)(nil),    // 7: pbentity.PraiseInfo
}
var file_praise_info_v1_praise_info_proto_depIdxs = []int32{
	7, // 0: praise_info.v1.PraiseInfoListResponse.list:type_name -> pbentity.PraiseInfo
	5, // 1: praise_info.v1.PraiseInfoGetListRes.data:type_name -> praise_info.v1.PraiseInfoListResponse
	4, // 2: praise_info.v1.praise_info.GetList:input_type -> praise_info.v1.PraiseInfoGetListReq
	0, // 3: praise_info.v1.praise_info.Create:input_type -> praise_info.v1.PraiseInfoCreateReq
	2, // 4: praise_info.v1.praise_info.Delete:input_type -> praise_info.v1.PraiseInfoDeleteReq
	6, // 5: praise_info.v1.praise_info.GetList:output_type -> praise_info.v1.PraiseInfoGetListRes
	1, // 6: praise_info.v1.praise_info.Create:output_type -> praise_info.v1.PraiseInfoCreateRes
	3, // 7: praise_info.v1.praise_info.Delete:output_type -> praise_info.v1.PraiseInfoDeleteRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_praise_info_v1_praise_info_proto_init() }
func file_praise_info_v1_praise_info_proto_init() {
	if File_praise_info_v1_praise_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_praise_info_v1_praise_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PraiseInfoCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_praise_info_v1_praise_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PraiseInfoCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_praise_info_v1_praise_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PraiseInfoDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_praise_info_v1_praise_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PraiseInfoDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_praise_info_v1_praise_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PraiseInfoGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_praise_info_v1_praise_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PraiseInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_praise_info_v1_praise_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PraiseInfoGetListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_praise_info_v1_praise_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_praise_info_v1_praise_info_proto_goTypes,
		DependencyIndexes: file_praise_info_v1_praise_info_proto_depIdxs,
		MessageInfos:      file_praise_info_v1_praise_info_proto_msgTypes,
	}.Build()
	File_praise_info_v1_praise_info_proto = out.File
	file_praise_info_v1_praise_info_proto_rawDesc = nil
	file_praise_info_v1_praise_info_proto_goTypes = nil
	file_praise_info_v1_praise_info_proto_depIdxs = nil
}
