// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PraiseInfoClient is the client API for PraiseInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PraiseInfoClient interface {
	GetList(ctx context.Context, in *PraiseInfoGetListReq, opts ...grpc.CallOption) (*PraiseInfoGetListRes, error)
	Create(ctx context.Context, in *PraiseInfoCreateReq, opts ...grpc.CallOption) (*PraiseInfoCreateRes, error)
	Delete(ctx context.Context, in *PraiseInfoDeleteReq, opts ...grpc.CallOption) (*PraiseInfoDeleteRes, error)
}

type praiseInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewPraiseInfoClient(cc grpc.ClientConnInterface) PraiseInfoClient {
	return &praiseInfoClient{cc}
}

func (c *praiseInfoClient) GetList(ctx context.Context, in *PraiseInfoGetListReq, opts ...grpc.CallOption) (*PraiseInfoGetListRes, error) {
	out := new(PraiseInfoGetListRes)
	err := c.cc.Invoke(ctx, "/praise_info.v1.praise_info/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *praiseInfoClient) Create(ctx context.Context, in *PraiseInfoCreateReq, opts ...grpc.CallOption) (*PraiseInfoCreateRes, error) {
	out := new(PraiseInfoCreateRes)
	err := c.cc.Invoke(ctx, "/praise_info.v1.praise_info/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *praiseInfoClient) Delete(ctx context.Context, in *PraiseInfoDeleteReq, opts ...grpc.CallOption) (*PraiseInfoDeleteRes, error) {
	out := new(PraiseInfoDeleteRes)
	err := c.cc.Invoke(ctx, "/praise_info.v1.praise_info/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PraiseInfoServer is the server API for PraiseInfo service.
// All implementations must embed UnimplementedPraiseInfoServer
// for forward compatibility
type PraiseInfoServer interface {
	GetList(context.Context, *PraiseInfoGetListReq) (*PraiseInfoGetListRes, error)
	Create(context.Context, *PraiseInfoCreateReq) (*PraiseInfoCreateRes, error)
	Delete(context.Context, *PraiseInfoDeleteReq) (*PraiseInfoDeleteRes, error)
	mustEmbedUnimplementedPraiseInfoServer()
}

// UnimplementedPraiseInfoServer must be embedded to have forward compatible implementations.
type UnimplementedPraiseInfoServer struct {
}

func (UnimplementedPraiseInfoServer) GetList(context.Context, *PraiseInfoGetListReq) (*PraiseInfoGetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedPraiseInfoServer) Create(context.Context, *PraiseInfoCreateReq) (*PraiseInfoCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPraiseInfoServer) Delete(context.Context, *PraiseInfoDeleteReq) (*PraiseInfoDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPraiseInfoServer) mustEmbedUnimplementedPraiseInfoServer() {}

// UnsafePraiseInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PraiseInfoServer will
// result in compilation errors.
type UnsafePraiseInfoServer interface {
	mustEmbedUnimplementedPraiseInfoServer()
}

func RegisterPraiseInfoServer(s grpc.ServiceRegistrar, srv PraiseInfoServer) {
	s.RegisterService(&PraiseInfo_ServiceDesc, srv)
}

func _PraiseInfo_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PraiseInfoGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PraiseInfoServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/praise_info.v1.praise_info/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PraiseInfoServer).GetList(ctx, req.(*PraiseInfoGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PraiseInfo_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PraiseInfoCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PraiseInfoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/praise_info.v1.praise_info/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PraiseInfoServer).Create(ctx, req.(*PraiseInfoCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PraiseInfo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PraiseInfoDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PraiseInfoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/praise_info.v1.praise_info/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PraiseInfoServer).Delete(ctx, req.(*PraiseInfoDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PraiseInfo_ServiceDesc is the grpc.ServiceDesc for PraiseInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PraiseInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "praise_info.v1.praise_info",
	HandlerType: (*PraiseInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _PraiseInfo_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PraiseInfo_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PraiseInfo_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "praise_info/v1/praise_info.proto",
}
