// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: user_info/v1/user_info.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 用户注册 ==========
type UserInfoRegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" dc:"用户名"`                                         // 用户名
	Password     string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" dc:"密码"`                                  // 密码
	Avatar       string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty" dc:"头像"`                                      // 头像
	Sex          uint32 `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty" dc:"1男 2女"`                                        // 1男 2女
	Sign         string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty" dc:"个性签名"`                                        // 个性签名
	SecretAnswer string `protobuf:"bytes,6,opt,name=secret_answer,json=secretAnswer,proto3" json:"secret_answer,omitempty" dc:"密保问题的答案"` // 密保问题的答案
}

func (x *UserInfoRegisterReq) Reset() {
	*x = UserInfoRegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRegisterReq) ProtoMessage() {}

func (x *UserInfoRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRegisterReq.ProtoReflect.Descriptor instead.
func (*UserInfoRegisterReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoRegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfoRegisterReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoRegisterReq) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfoRegisterReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *UserInfoRegisterReq) GetSecretAnswer() string {
	if x != nil {
		return x.SecretAnswer
	}
	return ""
}

type UserInfoRegisterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"用户ID"` // 用户ID
}

func (x *UserInfoRegisterRes) Reset() {
	*x = UserInfoRegisterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRegisterRes) ProtoMessage() {}

func (x *UserInfoRegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRegisterRes.ProtoReflect.Descriptor instead.
func (*UserInfoRegisterRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoRegisterRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ========== 用户登录 ==========
type UserInfoLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" dc:"用户名"`        // 用户名
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" dc:"密码"` // 密码
}

func (x *UserInfoLoginReq) Reset() {
	*x = UserInfoLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoLoginReq) ProtoMessage() {}

func (x *UserInfoLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoLoginReq.ProtoReflect.Descriptor instead.
func (*UserInfoLoginReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfoLoginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserInfoLoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" dc:"token类型"`                          // token类型
	Token    string        `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty" dc:"token字符串"`                       // token字符串
	ExpireIn uint32        `protobuf:"varint,3,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty" dc:"过期时间(秒)"` // 过期时间(秒)
	UserInfo *UserInfoBase `protobuf:"bytes,4,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty" dc:"用户基础信息"`   // 用户基础信息
}

func (x *UserInfoLoginRes) Reset() {
	*x = UserInfoLoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoLoginRes) ProtoMessage() {}

func (x *UserInfoLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoLoginRes.ProtoReflect.Descriptor instead.
func (*UserInfoLoginRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfoLoginRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserInfoLoginRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserInfoLoginRes) GetExpireIn() uint32 {
	if x != nil {
		return x.ExpireIn
	}
	return 0
}

func (x *UserInfoLoginRes) GetUserInfo() *UserInfoBase {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// ========== 用户信息 ==========
type UserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"用户ID"` // 用户ID
}

func (x *UserInfoReq) Reset() {
	*x = UserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoReq) ProtoMessage() {}

func (x *UserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoReq.ProtoReflect.Descriptor instead.
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo *UserInfoBase `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty" dc:"用户基础信息"` // 用户基础信息
}

func (x *UserInfoRes) Reset() {
	*x = UserInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRes) ProtoMessage() {}

func (x *UserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRes.ProtoReflect.Descriptor instead.
func (*UserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfoRes) GetUserInfo() *UserInfoBase {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// ========== 修改密码 ==========
type UserInfoUpdatePasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"用户ID"`                                           // 用户ID
	Password     string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty" dc:"新密码"`                                 // 新密码
	SecretAnswer string `protobuf:"bytes,3,opt,name=secret_answer,json=secretAnswer,proto3" json:"secret_answer,omitempty" dc:"密保问题的答案"` // 密保问题的答案
}

func (x *UserInfoUpdatePasswordReq) Reset() {
	*x = UserInfoUpdatePasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoUpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdatePasswordReq) ProtoMessage() {}

func (x *UserInfoUpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UserInfoUpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoUpdatePasswordReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoUpdatePasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfoUpdatePasswordReq) GetSecretAnswer() string {
	if x != nil {
		return x.SecretAnswer
	}
	return ""
}

type UserInfoUpdatePasswordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"用户ID"` // 用户ID
}

func (x *UserInfoUpdatePasswordRes) Reset() {
	*x = UserInfoUpdatePasswordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoUpdatePasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdatePasswordRes) ProtoMessage() {}

func (x *UserInfoUpdatePasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdatePasswordRes.ProtoReflect.Descriptor instead.
func (*UserInfoUpdatePasswordRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfoUpdatePasswordRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ========== 修改用户信息 ==========
type UserInfoUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"用户ID"`      //用户ID
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"昵称"`     //昵称
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty" dc:"头像"` //头像
}

func (x *UserInfoUpdateReq) Reset() {
	*x = UserInfoUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdateReq) ProtoMessage() {}

func (x *UserInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*UserInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoUpdateReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserInfoUpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"用户ID"` //用户ID
}

func (x *UserInfoUpdateRes) Reset() {
	*x = UserInfoUpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdateRes) ProtoMessage() {}

func (x *UserInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*UserInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{9}
}

func (x *UserInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ========== 公共结构 ==========
type UserInfoBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" dc:"用户ID"`       // 用户ID
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" dc:"用户名"`     // 用户名
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty" dc:"头像"`  // 头像
	Sex    uint32 `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty" dc:"性别"`       // 性别
	Sign   string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty" dc:"个性签名"`    // 个性签名
	Status uint32 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty" dc:"状态"` // 状态
}

func (x *UserInfoBase) Reset() {
	*x = UserInfoBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_info_v1_user_info_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoBase) ProtoMessage() {}

func (x *UserInfoBase) ProtoReflect() protoreflect.Message {
	mi := &file_user_info_v1_user_info_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoBase.ProtoReflect.Descriptor instead.
func (*UserInfoBase) Descriptor() ([]byte, []int) {
	return file_user_info_v1_user_info_proto_rawDescGZIP(), []int{10}
}

func (x *UserInfoBase) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoBase) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoBase) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfoBase) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *UserInfoBase) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_user_info_v1_user_info_proto protoreflect.FileDescriptor

var file_user_info_v1_user_info_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x13, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x10, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x8f, 0x01, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x49, 0x6e, 0x12, 0x34, 0x0a, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x43, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12,
	0x34, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x6c, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x4f, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x22, 0x23, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x32, 0x8a, 0x03, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x43,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x5e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x4a, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3f, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x40,
	0x5a, 0x3e, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x67, 0x6f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2d, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x72, 0x65, 0x66,
	0x61, 0x63, 0x6f, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_info_v1_user_info_proto_rawDescOnce sync.Once
	file_user_info_v1_user_info_proto_rawDescData = file_user_info_v1_user_info_proto_rawDesc
)

func file_user_info_v1_user_info_proto_rawDescGZIP() []byte {
	file_user_info_v1_user_info_proto_rawDescOnce.Do(func() {
		file_user_info_v1_user_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_info_v1_user_info_proto_rawDescData)
	})
	return file_user_info_v1_user_info_proto_rawDescData
}

var file_user_info_v1_user_info_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_info_v1_user_info_proto_goTypes = []interface{}{
	(*UserInfoRegisterReq)(nil),       // 0: user_info.UserInfoRegisterReq
	(*UserInfoRegisterRes)(nil),       // 1: user_info.UserInfoRegisterRes
	(*UserInfoLoginReq)(nil),          // 2: user_info.UserInfoLoginReq
	(*UserInfoLoginRes)(nil),          // 3: user_info.UserInfoLoginRes
	(*UserInfoReq)(nil),               // 4: user_info.UserInfoReq
	(*UserInfoRes)(nil),               // 5: user_info.UserInfoRes
	(*UserInfoUpdatePasswordReq)(nil), // 6: user_info.UserInfoUpdatePasswordReq
	(*UserInfoUpdatePasswordRes)(nil), // 7: user_info.UserInfoUpdatePasswordRes
	(*UserInfoUpdateReq)(nil),         // 8: user_info.UserInfoUpdateReq
	(*UserInfoUpdateRes)(nil),         // 9: user_info.UserInfoUpdateRes
	(*UserInfoBase)(nil),              // 10: user_info.UserInfoBase
}
var file_user_info_v1_user_info_proto_depIdxs = []int32{
	10, // 0: user_info.UserInfoLoginRes.user_info:type_name -> user_info.UserInfoBase
	10, // 1: user_info.UserInfoRes.user_info:type_name -> user_info.UserInfoBase
	2,  // 2: user_info.UserInfo.Login:input_type -> user_info.UserInfoLoginReq
	0,  // 3: user_info.UserInfo.Register:input_type -> user_info.UserInfoRegisterReq
	6,  // 4: user_info.UserInfo.UpdatePassword:input_type -> user_info.UserInfoUpdatePasswordReq
	8,  // 5: user_info.UserInfo.UpdateInfo:input_type -> user_info.UserInfoUpdateReq
	4,  // 6: user_info.UserInfo.GetUserInfo:input_type -> user_info.UserInfoReq
	3,  // 7: user_info.UserInfo.Login:output_type -> user_info.UserInfoLoginRes
	1,  // 8: user_info.UserInfo.Register:output_type -> user_info.UserInfoRegisterRes
	7,  // 9: user_info.UserInfo.UpdatePassword:output_type -> user_info.UserInfoUpdatePasswordRes
	9,  // 10: user_info.UserInfo.UpdateInfo:output_type -> user_info.UserInfoUpdateRes
	5,  // 11: user_info.UserInfo.GetUserInfo:output_type -> user_info.UserInfoRes
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_user_info_v1_user_info_proto_init() }
func file_user_info_v1_user_info_proto_init() {
	if File_user_info_v1_user_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_info_v1_user_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoRegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoRegisterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoLoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoUpdatePasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoUpdatePasswordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoUpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_info_v1_user_info_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_info_v1_user_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_info_v1_user_info_proto_goTypes,
		DependencyIndexes: file_user_info_v1_user_info_proto_depIdxs,
		MessageInfos:      file_user_info_v1_user_info_proto_msgTypes,
	}.Build()
	File_user_info_v1_user_info_proto = out.File
	file_user_info_v1_user_info_proto_rawDesc = nil
	file_user_info_v1_user_info_proto_goTypes = nil
	file_user_info_v1_user_info_proto_depIdxs = nil
}
