// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package goods

import (
	"shop-goframe-micro-service-refacotor/app/gateway-h5/api/goods"
	goods_images "shop-goframe-micro-service-refacotor/app/goods/api/goods_images/v1"
	goods_info "shop-goframe-micro-service-refacotor/app/goods/api/goods_info/v1"
	"shop-goframe-micro-service-refacotor/utility/middleware"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	GoodsInfoClient   goods_info.GoodsInfoClient
	GoodsImagesClient goods_images.GoodsImagesClient
}

func NewV1() goods.IGoodsV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("goods", grpcx.Client.ChainUnary(
		middleware.GrpcClientTimeout,
	))
	return &ControllerV1{
		GoodsInfoClient:   goods_info.NewGoodsInfoClient(conn),
		GoodsImagesClient: goods_images.NewGoodsImagesClient(conn),
	}
}
