// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package order

import (
	"shop-goframe-micro-service-refacotor/app/gateway-h5/api/order"
	order_info "shop-goframe-micro-service-refacotor/app/order/api/order_info/v1"
	"shop-goframe-micro-service-refacotor/utility/middleware"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	OrderInfoClient order_info.OrderInfoClient
}

func NewV1() order.IOrderV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("order", grpcx.Client.ChainUnary(
		middleware.GrpcClientTimeout,
	))
	return &ControllerV1{
		OrderInfoClient: order_info.NewOrderInfoClient(conn),
	}
}
