// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package flash_sale

import (
	flash_sale "shop-goframe-micro-service-refacotor/app/flash-sale/api/flash_sale/v1"
	flashSaleApi "shop-goframe-micro-service-refacotor/app/gateway-h5/api/flash_sale"
	"shop-goframe-micro-service-refacotor/utility/middleware"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	FlashSaleClient flash_sale.FlashSaleServiceClient
}

func NewV1() flashSaleApi.IFlashSaleV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("flash-sale", grpcx.Client.ChainUnary(
		middleware.GrpcClientTimeout,
	))
	return &ControllerV1{
		FlashSaleClient: flash_sale.NewFlashSaleServiceClient(conn),
	}
}
