// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package flash_sale

import (
	"context"

	flashSaleGrpc "shop-goframe-micro-service-refacotor/app/flash-sale/api/flash_sale/v1"
	"shop-goframe-micro-service-refacotor/app/gateway-h5/api/flash_sale/v1"
	"shop-goframe-micro-service-refacotor/utility/middleware"

	"github.com/gogf/gf/v2/errors/gcode"
	"github.com/gogf/gf/v2/errors/gerror"
)

func userIDFromCtx(ctx context.Context) (uint32, error) {
	userID, ok := ctx.Value(middleware.CtxUserId).(uint32)
	if !ok || userID == 0 {
		return 0, gerror.NewCode(gcode.CodeNotAuthorized, "无法获取用户信息，请重新登录")
	}
	return userID, nil
}

func buildGoodsItem(item *flashSaleGrpc.FlashSaleGoodsInfo) *v1.FlashSaleGoodsItem {
	if item == nil || item.Goods == nil {
		return nil
	}
	goods := item.Goods
	return &v1.FlashSaleGoodsItem{
		Id:             goods.Id,
		GoodsId:        goods.GoodsId,
		ActivityId:     goods.ActivityId,
		Title:          goods.Title,
		Description:    goods.Description,
		OriginalPrice:  goods.OriginalPrice,
		SalePrice:      goods.SalePrice,
		TotalStock:     goods.TotalStock,
		AvailableStock: item.AvailableStock,
		StartTime:      goods.StartTime,
		EndTime:        goods.EndTime,
		Status:         goods.Status,
		ImageUrl:       goods.ImageUrl,
		RemainSeconds:  item.RemainSeconds,
		CanBuy:         item.CanBuy,
	}
}
