// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: consignee_info/consignee_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/user/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type ConsigneeInfoCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`                              //
	IsDefault uint32 `protobuf:"varint,2,opt,name=IsDefault,proto3" json:"IsDefault,omitempty" dc:"默认地址1 非默认0"`        // 默认地址1 非默认0
	Name      string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                                   //
	Phone     string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`                                 //
	Province  string `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty"`                           //
	City      string `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty"`                                   //
	Town      string `protobuf:"bytes,7,opt,name=Town,proto3" json:"Town,omitempty" dc:"县区" dc:"县区" dc:"县区"`           // 县区
	Street    string `protobuf:"bytes,8,opt,name=Street,proto3" json:"Street,omitempty" dc:"街道乡镇" dc:"街道乡镇" dc:"街道乡镇"` // 街道乡镇
	Detail    string `protobuf:"bytes,9,opt,name=Detail,proto3" json:"Detail,omitempty" dc:"地址详情" dc:"地址详情" dc:"地址详情"` // 地址详情
}

func (x *ConsigneeInfoCreateReq) Reset() {
	*x = ConsigneeInfoCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoCreateReq) ProtoMessage() {}

func (x *ConsigneeInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoCreateReq.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{0}
}

func (x *ConsigneeInfoCreateReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConsigneeInfoCreateReq) GetIsDefault() uint32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ConsigneeInfoCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ConsigneeInfoCreateReq) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ConsigneeInfoCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ConsigneeInfoCreateRes) Reset() {
	*x = ConsigneeInfoCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoCreateRes) ProtoMessage() {}

func (x *ConsigneeInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoCreateRes.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{1}
}

func (x *ConsigneeInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConsigneeInfoGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
}

func (x *ConsigneeInfoGetListReq) Reset() {
	*x = ConsigneeInfoGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoGetListReq) ProtoMessage() {}

func (x *ConsigneeInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoGetListReq.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{2}
}

func (x *ConsigneeInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ConsigneeInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ConsigneeInfoUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty" dc:"收货地址表" dc:"收货地址表" dc:"收货地址表"`     // 收货地址表
	IsDefault uint32 `protobuf:"varint,2,opt,name=IsDefault,proto3" json:"IsDefault,omitempty" dc:"默认地址1 非默认0"`        // 默认地址1 非默认0
	Name      string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty" dc:"名字" dc:"名字" dc:"名字"`           // 名字
	Phone     string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty" dc:"手机" dc:"手机" dc:"手机"`         // 手机
	Province  string `protobuf:"bytes,5,opt,name=Province,proto3" json:"Province,omitempty" dc:"省会" dc:"省会" dc:"省会"`   //  省会
	City      string `protobuf:"bytes,6,opt,name=City,proto3" json:"City,omitempty" dc:"城市" dc:"城市" dc:"城市"`           //  城市
	Town      string `protobuf:"bytes,7,opt,name=Town,proto3" json:"Town,omitempty" dc:"县区" dc:"县区" dc:"县区"`           // 县区
	Street    string `protobuf:"bytes,8,opt,name=Street,proto3" json:"Street,omitempty" dc:"街道乡镇" dc:"街道乡镇" dc:"街道乡镇"` // 街道乡镇
	Detail    string `protobuf:"bytes,9,opt,name=Detail,proto3" json:"Detail,omitempty" dc:"地址详情" dc:"地址详情" dc:"地址详情"` // 地址详情
}

func (x *ConsigneeInfoUpdateReq) Reset() {
	*x = ConsigneeInfoUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoUpdateReq) ProtoMessage() {}

func (x *ConsigneeInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{3}
}

func (x *ConsigneeInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConsigneeInfoUpdateReq) GetIsDefault() uint32 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *ConsigneeInfoUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ConsigneeInfoUpdateReq) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ConsigneeInfoUpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ConsigneeInfoUpdateRes) Reset() {
	*x = ConsigneeInfoUpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoUpdateRes) ProtoMessage() {}

func (x *ConsigneeInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{4}
}

func (x *ConsigneeInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConsigneeInfoDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ConsigneeInfoDeleteReq) Reset() {
	*x = ConsigneeInfoDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoDeleteReq) ProtoMessage() {}

func (x *ConsigneeInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{5}
}

func (x *ConsigneeInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ConsigneeInfoDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConsigneeInfoDeleteRes) Reset() {
	*x = ConsigneeInfoDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoDeleteRes) ProtoMessage() {}

func (x *ConsigneeInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{6}
}

type ConsigneeInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*pbentity.ConsigneeInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page  uint32                    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  uint32                    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total uint32                    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ConsigneeInfoListResponse) Reset() {
	*x = ConsigneeInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoListResponse) ProtoMessage() {}

func (x *ConsigneeInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoListResponse.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoListResponse) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{7}
}

func (x *ConsigneeInfoListResponse) GetList() []*pbentity.ConsigneeInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ConsigneeInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ConsigneeInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ConsigneeInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ConsigneeInfoGetListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ConsigneeInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ConsigneeInfoGetListRes) Reset() {
	*x = ConsigneeInfoGetListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consignee_info_consignee_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsigneeInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsigneeInfoGetListRes) ProtoMessage() {}

func (x *ConsigneeInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_consignee_info_consignee_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsigneeInfoGetListRes.ProtoReflect.Descriptor instead.
func (*ConsigneeInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_consignee_info_consignee_info_proto_rawDescGZIP(), []int{8}
}

func (x *ConsigneeInfoGetListRes) GetData() *ConsigneeInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_consignee_info_consignee_info_proto protoreflect.FileDescriptor

var file_consignee_info_consignee_info_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x1d, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x49, 0x73, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x6f, 0x77, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x6f, 0x77, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a,
	0x17, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0xe4, 0x01, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49,
	0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x49, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43,
	0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x6f, 0x77, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x6f, 0x77, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x65,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x28, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x43,
	0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6e,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x58,
	0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x83, 0x03, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x5d, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x63,
	0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f,
	0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x5a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x63,
	0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f,
	0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x45,
	0x5a, 0x43, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x67, 0x6f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2d, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x72, 0x65, 0x66,
	0x61, 0x63, 0x6f, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x65, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consignee_info_consignee_info_proto_rawDescOnce sync.Once
	file_consignee_info_consignee_info_proto_rawDescData = file_consignee_info_consignee_info_proto_rawDesc
)

func file_consignee_info_consignee_info_proto_rawDescGZIP() []byte {
	file_consignee_info_consignee_info_proto_rawDescOnce.Do(func() {
		file_consignee_info_consignee_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_consignee_info_consignee_info_proto_rawDescData)
	})
	return file_consignee_info_consignee_info_proto_rawDescData
}

var file_consignee_info_consignee_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_consignee_info_consignee_info_proto_goTypes = []interface{}{
	(*ConsigneeInfoCreateReq)(nil),    // 0: consignee_info.ConsigneeInfoCreateReq
	(*ConsigneeInfoCreateRes)(nil),    // 1: consignee_info.ConsigneeInfoCreateRes
	(*ConsigneeInfoGetListReq)(nil),   // 2: consignee_info.ConsigneeInfoGetListReq
	(*ConsigneeInfoUpdateReq)(nil),    // 3: consignee_info.ConsigneeInfoUpdateReq
	(*ConsigneeInfoUpdateRes)(nil),    // 4: consignee_info.ConsigneeInfoUpdateRes
	(*ConsigneeInfoDeleteReq)(nil),    // 5: consignee_info.ConsigneeInfoDeleteReq
	(*ConsigneeInfoDeleteRes)(nil),    // 6: consignee_info.ConsigneeInfoDeleteRes
	(*ConsigneeInfoListResponse)(nil), // 7: consignee_info.ConsigneeInfoListResponse
	(*ConsigneeInfoGetListRes)(nil),   // 8: consignee_info.ConsigneeInfoGetListRes
	(*pbentity.ConsigneeInfo)(nil),    // 9: pbentity.ConsigneeInfo
}
var file_consignee_info_consignee_info_proto_depIdxs = []int32{
	9, // 0: consignee_info.ConsigneeInfoListResponse.list:type_name -> pbentity.ConsigneeInfo
	7, // 1: consignee_info.ConsigneeInfoGetListRes.data:type_name -> consignee_info.ConsigneeInfoListResponse
	2, // 2: consignee_info.consignee_info.GetList:input_type -> consignee_info.ConsigneeInfoGetListReq
	0, // 3: consignee_info.consignee_info.Create:input_type -> consignee_info.ConsigneeInfoCreateReq
	3, // 4: consignee_info.consignee_info.Update:input_type -> consignee_info.ConsigneeInfoUpdateReq
	5, // 5: consignee_info.consignee_info.Delete:input_type -> consignee_info.ConsigneeInfoDeleteReq
	8, // 6: consignee_info.consignee_info.GetList:output_type -> consignee_info.ConsigneeInfoGetListRes
	1, // 7: consignee_info.consignee_info.Create:output_type -> consignee_info.ConsigneeInfoCreateRes
	4, // 8: consignee_info.consignee_info.Update:output_type -> consignee_info.ConsigneeInfoUpdateRes
	6, // 9: consignee_info.consignee_info.Delete:output_type -> consignee_info.ConsigneeInfoDeleteRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_consignee_info_consignee_info_proto_init() }
func file_consignee_info_consignee_info_proto_init() {
	if File_consignee_info_consignee_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_consignee_info_consignee_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consignee_info_consignee_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consignee_info_consignee_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consignee_info_consignee_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consignee_info_consignee_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoUpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consignee_info_consignee_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consignee_info_consignee_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consignee_info_consignee_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consignee_info_consignee_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsigneeInfoGetListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consignee_info_consignee_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consignee_info_consignee_info_proto_goTypes,
		DependencyIndexes: file_consignee_info_consignee_info_proto_depIdxs,
		MessageInfos:      file_consignee_info_consignee_info_proto_msgTypes,
	}.Build()
	File_consignee_info_consignee_info_proto = out.File
	file_consignee_info_consignee_info_proto_rawDesc = nil
	file_consignee_info_consignee_info_proto_goTypes = nil
	file_consignee_info_consignee_info_proto_depIdxs = nil
}
