// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: collection_info/v1/collection_info.proto

package v1

import (
	pbentity "interaction/api/pbentity"
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type CollectionInfoCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId uint32 `protobuf:"varint,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty" dc:"对象id"` // 对象id
	Type     uint32 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty" dc:"收藏类型：1商品 2文章"` // 收藏类型：1商品 2文章
}

func (x *CollectionInfoCreateReq) Reset() {
	*x = CollectionInfoCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_info_v1_collection_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoCreateReq) ProtoMessage() {}

func (x *CollectionInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoCreateReq.ProtoReflect.Descriptor instead.
func (*CollectionInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionInfoCreateReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *CollectionInfoCreateReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type CollectionInfoCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CollectionInfoCreateRes) Reset() {
	*x = CollectionInfoCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_info_v1_collection_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoCreateRes) ProtoMessage() {}

func (x *CollectionInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoCreateRes.ProtoReflect.Descriptor instead.
func (*CollectionInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CollectionInfoDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                       //
	Type     uint32 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty" dc:"收藏类型：1商品 2文章"` // 收藏类型：1商品 2文章
	ObjectId uint32 `protobuf:"varint,3,opt,name=ObjectId,proto3" json:"ObjectId,omitempty" dc:"对象id"` // 对象id
}

func (x *CollectionInfoDeleteReq) Reset() {
	*x = CollectionInfoDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_info_v1_collection_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoDeleteReq) ProtoMessage() {}

func (x *CollectionInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*CollectionInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{2}
}

func (x *CollectionInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CollectionInfoDeleteReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CollectionInfoDeleteReq) GetObjectId() uint32 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type CollectionInfoDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CollectionInfoDeleteRes) Reset() {
	*x = CollectionInfoDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_info_v1_collection_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoDeleteRes) ProtoMessage() {}

func (x *CollectionInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*CollectionInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{3}
}

func (x *CollectionInfoDeleteRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CollectionInfoGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty" dc:"收藏类型：1商品 2文章"` // 收藏类型：1商品 2文章
	Page uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
}

func (x *CollectionInfoGetListReq) Reset() {
	*x = CollectionInfoGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_info_v1_collection_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoGetListReq) ProtoMessage() {}

func (x *CollectionInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoGetListReq.ProtoReflect.Descriptor instead.
func (*CollectionInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{4}
}

func (x *CollectionInfoGetListReq) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CollectionInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CollectionInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CollectionInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*pbentity.CollectionInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page  uint32                     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  uint32                     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total uint32                     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CollectionInfoListResponse) Reset() {
	*x = CollectionInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_info_v1_collection_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoListResponse) ProtoMessage() {}

func (x *CollectionInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoListResponse.ProtoReflect.Descriptor instead.
func (*CollectionInfoListResponse) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{5}
}

func (x *CollectionInfoListResponse) GetList() []*pbentity.CollectionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CollectionInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CollectionInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CollectionInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CollectionInfoGetListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *CollectionInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CollectionInfoGetListRes) Reset() {
	*x = CollectionInfoGetListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_collection_info_v1_collection_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionInfoGetListRes) ProtoMessage() {}

func (x *CollectionInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_collection_info_v1_collection_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionInfoGetListRes.ProtoReflect.Descriptor instead.
func (*CollectionInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_collection_info_v1_collection_info_proto_rawDescGZIP(), []int{6}
}

func (x *CollectionInfoGetListRes) GetData() *CollectionInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_collection_info_v1_collection_info_proto protoreflect.FileDescriptor

var file_collection_info_v1_collection_info_proto_rawDesc = []byte{
	0x0a, 0x28, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1e,
	0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49,
	0x0a, 0x17, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x29, 0x0a, 0x17, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x17, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22,
	0x29, 0x0a, 0x17, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a, 0x18, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x5e, 0x0a,
	0x18, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xc6, 0x02,
	0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x12, 0x67, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x64, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x4d, 0x5a, 0x4b, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x67,
	0x6f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2d, 0x72, 0x65, 0x66, 0x61, 0x63, 0x6f, 0x74, 0x6f, 0x72, 0x2f, 0x61,
	0x70, 0x70, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_collection_info_v1_collection_info_proto_rawDescOnce sync.Once
	file_collection_info_v1_collection_info_proto_rawDescData = file_collection_info_v1_collection_info_proto_rawDesc
)

func file_collection_info_v1_collection_info_proto_rawDescGZIP() []byte {
	file_collection_info_v1_collection_info_proto_rawDescOnce.Do(func() {
		file_collection_info_v1_collection_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_collection_info_v1_collection_info_proto_rawDescData)
	})
	return file_collection_info_v1_collection_info_proto_rawDescData
}

var file_collection_info_v1_collection_info_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_collection_info_v1_collection_info_proto_goTypes = []interface{}{
	(*CollectionInfoCreateReq)(nil),    // 0: collection_info.v1.CollectionInfoCreateReq
	(*CollectionInfoCreateRes)(nil),    // 1: collection_info.v1.CollectionInfoCreateRes
	(*CollectionInfoDeleteReq)(nil),    // 2: collection_info.v1.CollectionInfoDeleteReq
	(*CollectionInfoDeleteRes)(nil),    // 3: collection_info.v1.CollectionInfoDeleteRes
	(*CollectionInfoGetListReq)(nil),   // 4: collection_info.v1.CollectionInfoGetListReq
	(*CollectionInfoListResponse)(nil), // 5: collection_info.v1.CollectionInfoListResponse
	(*CollectionInfoGetListRes)(nil),   // 6: collection_info.v1.CollectionInfoGetListRes
	(*pbentity.CollectionInfo)(nil),    // 7: pbentity.CollectionInfo
}
var file_collection_info_v1_collection_info_proto_depIdxs = []int32{
	7, // 0: collection_info.v1.CollectionInfoListResponse.list:type_name -> pbentity.CollectionInfo
	5, // 1: collection_info.v1.CollectionInfoGetListRes.data:type_name -> collection_info.v1.CollectionInfoListResponse
	4, // 2: collection_info.v1.collection_info.GetList:input_type -> collection_info.v1.CollectionInfoGetListReq
	0, // 3: collection_info.v1.collection_info.Create:input_type -> collection_info.v1.CollectionInfoCreateReq
	2, // 4: collection_info.v1.collection_info.Delete:input_type -> collection_info.v1.CollectionInfoDeleteReq
	6, // 5: collection_info.v1.collection_info.GetList:output_type -> collection_info.v1.CollectionInfoGetListRes
	1, // 6: collection_info.v1.collection_info.Create:output_type -> collection_info.v1.CollectionInfoCreateRes
	3, // 7: collection_info.v1.collection_info.Delete:output_type -> collection_info.v1.CollectionInfoDeleteRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_collection_info_v1_collection_info_proto_init() }
func file_collection_info_v1_collection_info_proto_init() {
	if File_collection_info_v1_collection_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_collection_info_v1_collection_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionInfoCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collection_info_v1_collection_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionInfoCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collection_info_v1_collection_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionInfoDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collection_info_v1_collection_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionInfoDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collection_info_v1_collection_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionInfoGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collection_info_v1_collection_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_collection_info_v1_collection_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionInfoGetListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_collection_info_v1_collection_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collection_info_v1_collection_info_proto_goTypes,
		DependencyIndexes: file_collection_info_v1_collection_info_proto_depIdxs,
		MessageInfos:      file_collection_info_v1_collection_info_proto_msgTypes,
	}.Build()
	File_collection_info_v1_collection_info_proto = out.File
	file_collection_info_v1_collection_info_proto_rawDesc = nil
	file_collection_info_v1_collection_info_proto_goTypes = nil
	file_collection_info_v1_collection_info_proto_depIdxs = nil
}
