// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlashSaleServiceClient is the client API for FlashSaleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlashSaleServiceClient interface {
	GetFlashSaleGoodsList(ctx context.Context, in *FlashSaleGoodsListReq, opts ...grpc.CallOption) (*FlashSaleGoodsListRes, error)
	GetFlashSaleGoodsDetail(ctx context.Context, in *FlashSaleGoodsDetailReq, opts ...grpc.CallOption) (*FlashSaleGoodsDetailRes, error)
	CreateFlashSaleOrder(ctx context.Context, in *CreateFlashSaleOrderReq, opts ...grpc.CallOption) (*CreateFlashSaleOrderRes, error)
	GetFlashSaleResult(ctx context.Context, in *GetFlashSaleResultReq, opts ...grpc.CallOption) (*GetFlashSaleResultRes, error)
}

type flashSaleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlashSaleServiceClient(cc grpc.ClientConnInterface) FlashSaleServiceClient {
	return &flashSaleServiceClient{cc}
}

func (c *flashSaleServiceClient) GetFlashSaleGoodsList(ctx context.Context, in *FlashSaleGoodsListReq, opts ...grpc.CallOption) (*FlashSaleGoodsListRes, error) {
	out := new(FlashSaleGoodsListRes)
	err := c.cc.Invoke(ctx, "/flash_sale.v1.FlashSaleService/GetFlashSaleGoodsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flashSaleServiceClient) GetFlashSaleGoodsDetail(ctx context.Context, in *FlashSaleGoodsDetailReq, opts ...grpc.CallOption) (*FlashSaleGoodsDetailRes, error) {
	out := new(FlashSaleGoodsDetailRes)
	err := c.cc.Invoke(ctx, "/flash_sale.v1.FlashSaleService/GetFlashSaleGoodsDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flashSaleServiceClient) CreateFlashSaleOrder(ctx context.Context, in *CreateFlashSaleOrderReq, opts ...grpc.CallOption) (*CreateFlashSaleOrderRes, error) {
	out := new(CreateFlashSaleOrderRes)
	err := c.cc.Invoke(ctx, "/flash_sale.v1.FlashSaleService/CreateFlashSaleOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flashSaleServiceClient) GetFlashSaleResult(ctx context.Context, in *GetFlashSaleResultReq, opts ...grpc.CallOption) (*GetFlashSaleResultRes, error) {
	out := new(GetFlashSaleResultRes)
	err := c.cc.Invoke(ctx, "/flash_sale.v1.FlashSaleService/GetFlashSaleResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlashSaleServiceServer is the server API for FlashSaleService service.
// All implementations must embed UnimplementedFlashSaleServiceServer
// for forward compatibility
type FlashSaleServiceServer interface {
	GetFlashSaleGoodsList(context.Context, *FlashSaleGoodsListReq) (*FlashSaleGoodsListRes, error)
	GetFlashSaleGoodsDetail(context.Context, *FlashSaleGoodsDetailReq) (*FlashSaleGoodsDetailRes, error)
	CreateFlashSaleOrder(context.Context, *CreateFlashSaleOrderReq) (*CreateFlashSaleOrderRes, error)
	GetFlashSaleResult(context.Context, *GetFlashSaleResultReq) (*GetFlashSaleResultRes, error)
	mustEmbedUnimplementedFlashSaleServiceServer()
}

// UnimplementedFlashSaleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFlashSaleServiceServer struct {
}

func (UnimplementedFlashSaleServiceServer) GetFlashSaleGoodsList(context.Context, *FlashSaleGoodsListReq) (*FlashSaleGoodsListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlashSaleGoodsList not implemented")
}
func (UnimplementedFlashSaleServiceServer) GetFlashSaleGoodsDetail(context.Context, *FlashSaleGoodsDetailReq) (*FlashSaleGoodsDetailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlashSaleGoodsDetail not implemented")
}
func (UnimplementedFlashSaleServiceServer) CreateFlashSaleOrder(context.Context, *CreateFlashSaleOrderReq) (*CreateFlashSaleOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFlashSaleOrder not implemented")
}
func (UnimplementedFlashSaleServiceServer) GetFlashSaleResult(context.Context, *GetFlashSaleResultReq) (*GetFlashSaleResultRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlashSaleResult not implemented")
}
func (UnimplementedFlashSaleServiceServer) mustEmbedUnimplementedFlashSaleServiceServer() {}

// UnsafeFlashSaleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlashSaleServiceServer will
// result in compilation errors.
type UnsafeFlashSaleServiceServer interface {
	mustEmbedUnimplementedFlashSaleServiceServer()
}

func RegisterFlashSaleServiceServer(s grpc.ServiceRegistrar, srv FlashSaleServiceServer) {
	s.RegisterService(&FlashSaleService_ServiceDesc, srv)
}

func _FlashSaleService_GetFlashSaleGoodsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashSaleGoodsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashSaleServiceServer).GetFlashSaleGoodsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flash_sale.v1.FlashSaleService/GetFlashSaleGoodsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashSaleServiceServer).GetFlashSaleGoodsList(ctx, req.(*FlashSaleGoodsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlashSaleService_GetFlashSaleGoodsDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashSaleGoodsDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashSaleServiceServer).GetFlashSaleGoodsDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flash_sale.v1.FlashSaleService/GetFlashSaleGoodsDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashSaleServiceServer).GetFlashSaleGoodsDetail(ctx, req.(*FlashSaleGoodsDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlashSaleService_CreateFlashSaleOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFlashSaleOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashSaleServiceServer).CreateFlashSaleOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flash_sale.v1.FlashSaleService/CreateFlashSaleOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashSaleServiceServer).CreateFlashSaleOrder(ctx, req.(*CreateFlashSaleOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlashSaleService_GetFlashSaleResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlashSaleResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashSaleServiceServer).GetFlashSaleResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flash_sale.v1.FlashSaleService/GetFlashSaleResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashSaleServiceServer).GetFlashSaleResult(ctx, req.(*GetFlashSaleResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FlashSaleService_ServiceDesc is the grpc.ServiceDesc for FlashSaleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlashSaleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flash_sale.v1.FlashSaleService",
	HandlerType: (*FlashSaleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlashSaleGoodsList",
			Handler:    _FlashSaleService_GetFlashSaleGoodsList_Handler,
		},
		{
			MethodName: "GetFlashSaleGoodsDetail",
			Handler:    _FlashSaleService_GetFlashSaleGoodsDetail_Handler,
		},
		{
			MethodName: "CreateFlashSaleOrder",
			Handler:    _FlashSaleService_CreateFlashSaleOrder_Handler,
		},
		{
			MethodName: "GetFlashSaleResult",
			Handler:    _FlashSaleService_GetFlashSaleResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flash_sale/v1/flash_sale.proto",
}
