// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: position_info/v1/position_info.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/banner/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type PositionInfoCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PicUrl    string `protobuf:"bytes,1,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"图片链接"`       // 图片链接
	GoodsName string `protobuf:"bytes,2,opt,name=GoodsName,proto3" json:"GoodsName,omitempty" dc:"商品名称"` // 商品名称
	Link      string `protobuf:"bytes,3,opt,name=Link,proto3" json:"Link,omitempty" dc:"跳转链接"`           // 跳转链接
	Sort      uint32 `protobuf:"varint,4,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"排序"`            // 排序
	GoodsId   uint32 `protobuf:"varint,5,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品id"`    // 商品id
}

func (x *PositionInfoCreateReq) Reset() {
	*x = PositionInfoCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoCreateReq) ProtoMessage() {}

func (x *PositionInfoCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoCreateReq.ProtoReflect.Descriptor instead.
func (*PositionInfoCreateReq) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{0}
}

func (x *PositionInfoCreateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *PositionInfoCreateReq) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *PositionInfoCreateReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PositionInfoCreateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PositionInfoCreateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type PositionInfoCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PositionInfoCreateRes) Reset() {
	*x = PositionInfoCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoCreateRes) ProtoMessage() {}

func (x *PositionInfoCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoCreateRes.ProtoReflect.Descriptor instead.
func (*PositionInfoCreateRes) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{1}
}

func (x *PositionInfoCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PositionInfoUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                        //
	PicUrl    string `protobuf:"bytes,2,opt,name=PicUrl,proto3" json:"PicUrl,omitempty" dc:"图片链接"`       // 图片链接
	GoodsName string `protobuf:"bytes,3,opt,name=GoodsName,proto3" json:"GoodsName,omitempty" dc:"商品名称"` // 商品名称
	Link      string `protobuf:"bytes,4,opt,name=Link,proto3" json:"Link,omitempty" dc:"跳转链接"`           // 跳转链接
	Sort      uint32 `protobuf:"varint,5,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"排序"`            // 排序
	GoodsId   uint32 `protobuf:"varint,6,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品id"`    // 商品id
}

func (x *PositionInfoUpdateReq) Reset() {
	*x = PositionInfoUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoUpdateReq) ProtoMessage() {}

func (x *PositionInfoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoUpdateReq.ProtoReflect.Descriptor instead.
func (*PositionInfoUpdateReq) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{2}
}

func (x *PositionInfoUpdateReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionInfoUpdateReq) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *PositionInfoUpdateReq) GetGoodsName() string {
	if x != nil {
		return x.GoodsName
	}
	return ""
}

func (x *PositionInfoUpdateReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PositionInfoUpdateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PositionInfoUpdateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

type PositionInfoUpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PositionInfoUpdateRes) Reset() {
	*x = PositionInfoUpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoUpdateRes) ProtoMessage() {}

func (x *PositionInfoUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoUpdateRes.ProtoReflect.Descriptor instead.
func (*PositionInfoUpdateRes) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{3}
}

func (x *PositionInfoUpdateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PositionInfoDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PositionInfoDeleteReq) Reset() {
	*x = PositionInfoDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoDeleteReq) ProtoMessage() {}

func (x *PositionInfoDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoDeleteReq.ProtoReflect.Descriptor instead.
func (*PositionInfoDeleteReq) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{4}
}

func (x *PositionInfoDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PositionInfoDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PositionInfoDeleteRes) Reset() {
	*x = PositionInfoDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoDeleteRes) ProtoMessage() {}

func (x *PositionInfoDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoDeleteRes.ProtoReflect.Descriptor instead.
func (*PositionInfoDeleteRes) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{5}
}

type PositionInfoGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sort uint32 `protobuf:"varint,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Page uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
}

func (x *PositionInfoGetListReq) Reset() {
	*x = PositionInfoGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoGetListReq) ProtoMessage() {}

func (x *PositionInfoGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoGetListReq.ProtoReflect.Descriptor instead.
func (*PositionInfoGetListReq) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{6}
}

func (x *PositionInfoGetListReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *PositionInfoGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PositionInfoGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PositionInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*pbentity.PositionInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page  uint32                   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  uint32                   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total uint32                   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *PositionInfoListResponse) Reset() {
	*x = PositionInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoListResponse) ProtoMessage() {}

func (x *PositionInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoListResponse.ProtoReflect.Descriptor instead.
func (*PositionInfoListResponse) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{7}
}

func (x *PositionInfoListResponse) GetList() []*pbentity.PositionInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PositionInfoListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PositionInfoListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PositionInfoListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PositionInfoGetListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *PositionInfoListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PositionInfoGetListRes) Reset() {
	*x = PositionInfoGetListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_position_info_v1_position_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PositionInfoGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionInfoGetListRes) ProtoMessage() {}

func (x *PositionInfoGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_position_info_v1_position_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionInfoGetListRes.ProtoReflect.Descriptor instead.
func (*PositionInfoGetListRes) Descriptor() ([]byte, []int) {
	return file_position_info_v1_position_info_proto_rawDescGZIP(), []int{8}
}

func (x *PositionInfoGetListRes) GetData() *PositionInfoListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_position_info_v1_position_info_proto protoreflect.FileDescriptor

var file_position_info_v1_position_info_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x6f,
	0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x9f, 0x01, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x69, 0x63,
	0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x15,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x54,
	0x0a, 0x16, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x18, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x58, 0x0a, 0x16, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x8a, 0x03, 0x0a, 0x0d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x5f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x28, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x27, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x27, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x27,
	0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x42, 0x46, 0x5a, 0x44, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x67, 0x6f, 0x66, 0x72, 0x61,
	0x6d, 0x65, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2d, 0x72, 0x65, 0x66, 0x61, 0x63, 0x6f, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_position_info_v1_position_info_proto_rawDescOnce sync.Once
	file_position_info_v1_position_info_proto_rawDescData = file_position_info_v1_position_info_proto_rawDesc
)

func file_position_info_v1_position_info_proto_rawDescGZIP() []byte {
	file_position_info_v1_position_info_proto_rawDescOnce.Do(func() {
		file_position_info_v1_position_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_position_info_v1_position_info_proto_rawDescData)
	})
	return file_position_info_v1_position_info_proto_rawDescData
}

var file_position_info_v1_position_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_position_info_v1_position_info_proto_goTypes = []interface{}{
	(*PositionInfoCreateReq)(nil),    // 0: position_info.v1.PositionInfoCreateReq
	(*PositionInfoCreateRes)(nil),    // 1: position_info.v1.PositionInfoCreateRes
	(*PositionInfoUpdateReq)(nil),    // 2: position_info.v1.PositionInfoUpdateReq
	(*PositionInfoUpdateRes)(nil),    // 3: position_info.v1.PositionInfoUpdateRes
	(*PositionInfoDeleteReq)(nil),    // 4: position_info.v1.PositionInfoDeleteReq
	(*PositionInfoDeleteRes)(nil),    // 5: position_info.v1.PositionInfoDeleteRes
	(*PositionInfoGetListReq)(nil),   // 6: position_info.v1.PositionInfoGetListReq
	(*PositionInfoListResponse)(nil), // 7: position_info.v1.PositionInfoListResponse
	(*PositionInfoGetListRes)(nil),   // 8: position_info.v1.PositionInfoGetListRes
	(*pbentity.PositionInfo)(nil),    // 9: pbentity.PositionInfo
}
var file_position_info_v1_position_info_proto_depIdxs = []int32{
	9, // 0: position_info.v1.PositionInfoListResponse.list:type_name -> pbentity.PositionInfo
	7, // 1: position_info.v1.PositionInfoGetListRes.data:type_name -> position_info.v1.PositionInfoListResponse
	6, // 2: position_info.v1.position_info.GetList:input_type -> position_info.v1.PositionInfoGetListReq
	0, // 3: position_info.v1.position_info.Create:input_type -> position_info.v1.PositionInfoCreateReq
	2, // 4: position_info.v1.position_info.Update:input_type -> position_info.v1.PositionInfoUpdateReq
	4, // 5: position_info.v1.position_info.Delete:input_type -> position_info.v1.PositionInfoDeleteReq
	8, // 6: position_info.v1.position_info.GetList:output_type -> position_info.v1.PositionInfoGetListRes
	1, // 7: position_info.v1.position_info.Create:output_type -> position_info.v1.PositionInfoCreateRes
	3, // 8: position_info.v1.position_info.Update:output_type -> position_info.v1.PositionInfoUpdateRes
	5, // 9: position_info.v1.position_info.Delete:output_type -> position_info.v1.PositionInfoDeleteRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_position_info_v1_position_info_proto_init() }
func file_position_info_v1_position_info_proto_init() {
	if File_position_info_v1_position_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_position_info_v1_position_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_info_v1_position_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_info_v1_position_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_info_v1_position_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoUpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_info_v1_position_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_info_v1_position_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_info_v1_position_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_info_v1_position_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_position_info_v1_position_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PositionInfoGetListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_position_info_v1_position_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_position_info_v1_position_info_proto_goTypes,
		DependencyIndexes: file_position_info_v1_position_info_proto_depIdxs,
		MessageInfos:      file_position_info_v1_position_info_proto_msgTypes,
	}.Build()
	File_position_info_v1_position_info_proto = out.File
	file_position_info_v1_position_info_proto_rawDesc = nil
	file_position_info_v1_position_info_proto_goTypes = nil
	file_position_info_v1_position_info_proto_depIdxs = nil
}
