// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: goods_images/v1/goods_images.proto

package v1

import (
	reflect "reflect"
	pbentity "shop-goframe-micro-service-refacotor/app/goods/api/pbentity"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 新增消息定义
type GoodsImagesCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId uint32 `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty" dc:"商品ID"`            // 商品ID
	FileId  uint32 `protobuf:"varint,2,opt,name=FileId,proto3" json:"FileId,omitempty" dc:"文件ID（关联file_info）"` // 文件ID（关联file_info）
	Sort    uint32 `protobuf:"varint,3,opt,name=Sort,proto3" json:"Sort,omitempty" dc:"排序"`                    // 排序
	Url     string `protobuf:"bytes,4,opt,name=Url,proto3" json:"Url,omitempty" dc:"七牛云url"`                   // 七牛云url
}

func (x *GoodsImagesCreateReq) Reset() {
	*x = GoodsImagesCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_images_v1_goods_images_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsImagesCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesCreateReq) ProtoMessage() {}

func (x *GoodsImagesCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesCreateReq.ProtoReflect.Descriptor instead.
func (*GoodsImagesCreateReq) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsImagesCreateReq) GetGoodsId() uint32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsImagesCreateReq) GetFileId() uint32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *GoodsImagesCreateReq) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *GoodsImagesCreateReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GoodsImagesCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GoodsImagesCreateRes) Reset() {
	*x = GoodsImagesCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_images_v1_goods_images_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsImagesCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesCreateRes) ProtoMessage() {}

func (x *GoodsImagesCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesCreateRes.ProtoReflect.Descriptor instead.
func (*GoodsImagesCreateRes) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsImagesCreateRes) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsImagesDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GoodsImagesDeleteReq) Reset() {
	*x = GoodsImagesDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_images_v1_goods_images_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsImagesDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesDeleteReq) ProtoMessage() {}

func (x *GoodsImagesDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesDeleteReq.ProtoReflect.Descriptor instead.
func (*GoodsImagesDeleteReq) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsImagesDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsImagesDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GoodsImagesDeleteRes) Reset() {
	*x = GoodsImagesDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_images_v1_goods_images_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsImagesDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesDeleteRes) ProtoMessage() {}

func (x *GoodsImagesDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesDeleteRes.ProtoReflect.Descriptor instead.
func (*GoodsImagesDeleteRes) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{3}
}

type GoodsImagesGetListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty" dc:"修改：字段编号必须从1开始递增"` // 修改：字段编号必须从1开始递增
}

func (x *GoodsImagesGetListReq) Reset() {
	*x = GoodsImagesGetListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_images_v1_goods_images_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsImagesGetListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesGetListReq) ProtoMessage() {}

func (x *GoodsImagesGetListReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesGetListReq.ProtoReflect.Descriptor instead.
func (*GoodsImagesGetListReq) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{4}
}

func (x *GoodsImagesGetListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsImagesGetListReq) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GoodsImagesListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*pbentity.GoodsImages `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page  uint32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size  uint32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total uint32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GoodsImagesListResponse) Reset() {
	*x = GoodsImagesListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_images_v1_goods_images_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsImagesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesListResponse) ProtoMessage() {}

func (x *GoodsImagesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesListResponse.ProtoReflect.Descriptor instead.
func (*GoodsImagesListResponse) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{5}
}

func (x *GoodsImagesListResponse) GetList() []*pbentity.GoodsImages {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GoodsImagesListResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GoodsImagesListResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GoodsImagesListResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GoodsImagesGetListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *GoodsImagesListResponse `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GoodsImagesGetListRes) Reset() {
	*x = GoodsImagesGetListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_images_v1_goods_images_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsImagesGetListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsImagesGetListRes) ProtoMessage() {}

func (x *GoodsImagesGetListRes) ProtoReflect() protoreflect.Message {
	mi := &file_goods_images_v1_goods_images_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsImagesGetListRes.ProtoReflect.Descriptor instead.
func (*GoodsImagesGetListRes) Descriptor() ([]byte, []int) {
	return file_goods_images_v1_goods_images_proto_rawDescGZIP(), []int{6}
}

func (x *GoodsImagesGetListRes) GetData() *GoodsImagesListResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_goods_images_v1_goods_images_proto protoreflect.FileDescriptor

var file_goods_images_v1_goods_images_proto_rawDesc = []byte{
	0x0a, 0x22, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f,
	0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x14, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x47, 0x6f, 0x6f,
	0x64, 0x73, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55,
	0x72, 0x6c, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x15, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x82, 0x01, 0x0a, 0x17,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x22, 0x55, 0x0a, 0x15, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x9f, 0x02, 0x0a, 0x0c, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x5b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x26, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x25, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x58, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64,
	0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x25, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x73, 0x68, 0x6f,
	0x70, 0x2d, 0x67, 0x6f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goods_images_v1_goods_images_proto_rawDescOnce sync.Once
	file_goods_images_v1_goods_images_proto_rawDescData = file_goods_images_v1_goods_images_proto_rawDesc
)

func file_goods_images_v1_goods_images_proto_rawDescGZIP() []byte {
	file_goods_images_v1_goods_images_proto_rawDescOnce.Do(func() {
		file_goods_images_v1_goods_images_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_images_v1_goods_images_proto_rawDescData)
	})
	return file_goods_images_v1_goods_images_proto_rawDescData
}

var file_goods_images_v1_goods_images_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_goods_images_v1_goods_images_proto_goTypes = []interface{}{
	(*GoodsImagesCreateReq)(nil),    // 0: goods_images.v1.GoodsImagesCreateReq
	(*GoodsImagesCreateRes)(nil),    // 1: goods_images.v1.GoodsImagesCreateRes
	(*GoodsImagesDeleteReq)(nil),    // 2: goods_images.v1.GoodsImagesDeleteReq
	(*GoodsImagesDeleteRes)(nil),    // 3: goods_images.v1.GoodsImagesDeleteRes
	(*GoodsImagesGetListReq)(nil),   // 4: goods_images.v1.GoodsImagesGetListReq
	(*GoodsImagesListResponse)(nil), // 5: goods_images.v1.GoodsImagesListResponse
	(*GoodsImagesGetListRes)(nil),   // 6: goods_images.v1.GoodsImagesGetListRes
	(*pbentity.GoodsImages)(nil),    // 7: pbentity.GoodsImages
}
var file_goods_images_v1_goods_images_proto_depIdxs = []int32{
	7, // 0: goods_images.v1.GoodsImagesListResponse.list:type_name -> pbentity.GoodsImages
	5, // 1: goods_images.v1.GoodsImagesGetListRes.data:type_name -> goods_images.v1.GoodsImagesListResponse
	4, // 2: goods_images.v1.goods_images.GetList:input_type -> goods_images.v1.GoodsImagesGetListReq
	0, // 3: goods_images.v1.goods_images.Create:input_type -> goods_images.v1.GoodsImagesCreateReq
	2, // 4: goods_images.v1.goods_images.Delete:input_type -> goods_images.v1.GoodsImagesDeleteReq
	6, // 5: goods_images.v1.goods_images.GetList:output_type -> goods_images.v1.GoodsImagesGetListRes
	1, // 6: goods_images.v1.goods_images.Create:output_type -> goods_images.v1.GoodsImagesCreateRes
	3, // 7: goods_images.v1.goods_images.Delete:output_type -> goods_images.v1.GoodsImagesDeleteRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_goods_images_v1_goods_images_proto_init() }
func file_goods_images_v1_goods_images_proto_init() {
	if File_goods_images_v1_goods_images_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goods_images_v1_goods_images_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsImagesCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_images_v1_goods_images_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsImagesCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_images_v1_goods_images_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsImagesDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_images_v1_goods_images_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsImagesDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_images_v1_goods_images_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsImagesGetListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_images_v1_goods_images_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsImagesListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_images_v1_goods_images_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsImagesGetListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_images_v1_goods_images_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_images_v1_goods_images_proto_goTypes,
		DependencyIndexes: file_goods_images_v1_goods_images_proto_depIdxs,
		MessageInfos:      file_goods_images_v1_goods_images_proto_msgTypes,
	}.Build()
	File_goods_images_v1_goods_images_proto = out.File
	file_goods_images_v1_goods_images_proto_rawDesc = nil
	file_goods_images_v1_goods_images_proto_goTypes = nil
	file_goods_images_v1_goods_images_proto_depIdxs = nil
}
