// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoodsImagesClient is the client API for GoodsImages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsImagesClient interface {
	// 商品图片列表
	GetList(ctx context.Context, in *GoodsImagesGetListReq, opts ...grpc.CallOption) (*GoodsImagesGetListRes, error)
	// 创建商品图片
	Create(ctx context.Context, in *GoodsImagesCreateReq, opts ...grpc.CallOption) (*GoodsImagesCreateRes, error)
	// 删除商品图片
	Delete(ctx context.Context, in *GoodsImagesDeleteReq, opts ...grpc.CallOption) (*GoodsImagesDeleteRes, error)
}

type goodsImagesClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsImagesClient(cc grpc.ClientConnInterface) GoodsImagesClient {
	return &goodsImagesClient{cc}
}

func (c *goodsImagesClient) GetList(ctx context.Context, in *GoodsImagesGetListReq, opts ...grpc.CallOption) (*GoodsImagesGetListRes, error) {
	out := new(GoodsImagesGetListRes)
	err := c.cc.Invoke(ctx, "/goods_images.v1.goods_images/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsImagesClient) Create(ctx context.Context, in *GoodsImagesCreateReq, opts ...grpc.CallOption) (*GoodsImagesCreateRes, error) {
	out := new(GoodsImagesCreateRes)
	err := c.cc.Invoke(ctx, "/goods_images.v1.goods_images/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsImagesClient) Delete(ctx context.Context, in *GoodsImagesDeleteReq, opts ...grpc.CallOption) (*GoodsImagesDeleteRes, error) {
	out := new(GoodsImagesDeleteRes)
	err := c.cc.Invoke(ctx, "/goods_images.v1.goods_images/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsImagesServer is the server API for GoodsImages service.
// All implementations must embed UnimplementedGoodsImagesServer
// for forward compatibility
type GoodsImagesServer interface {
	// 商品图片列表
	GetList(context.Context, *GoodsImagesGetListReq) (*GoodsImagesGetListRes, error)
	// 创建商品图片
	Create(context.Context, *GoodsImagesCreateReq) (*GoodsImagesCreateRes, error)
	// 删除商品图片
	Delete(context.Context, *GoodsImagesDeleteReq) (*GoodsImagesDeleteRes, error)
	mustEmbedUnimplementedGoodsImagesServer()
}

// UnimplementedGoodsImagesServer must be embedded to have forward compatible implementations.
type UnimplementedGoodsImagesServer struct {
}

func (UnimplementedGoodsImagesServer) GetList(context.Context, *GoodsImagesGetListReq) (*GoodsImagesGetListRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedGoodsImagesServer) Create(context.Context, *GoodsImagesCreateReq) (*GoodsImagesCreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGoodsImagesServer) Delete(context.Context, *GoodsImagesDeleteReq) (*GoodsImagesDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGoodsImagesServer) mustEmbedUnimplementedGoodsImagesServer() {}

// UnsafeGoodsImagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsImagesServer will
// result in compilation errors.
type UnsafeGoodsImagesServer interface {
	mustEmbedUnimplementedGoodsImagesServer()
}

func RegisterGoodsImagesServer(s grpc.ServiceRegistrar, srv GoodsImagesServer) {
	s.RegisterService(&GoodsImages_ServiceDesc, srv)
}

func _GoodsImages_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsImagesGetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsImagesServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods_images.v1.goods_images/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsImagesServer).GetList(ctx, req.(*GoodsImagesGetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsImages_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsImagesCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsImagesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods_images.v1.goods_images/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsImagesServer).Create(ctx, req.(*GoodsImagesCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsImages_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsImagesDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsImagesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goods_images.v1.goods_images/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsImagesServer).Delete(ctx, req.(*GoodsImagesDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsImages_ServiceDesc is the grpc.ServiceDesc for GoodsImages service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsImages_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goods_images.v1.goods_images",
	HandlerType: (*GoodsImagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _GoodsImages_GetList_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _GoodsImages_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GoodsImages_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods_images/v1/goods_images.proto",
}
