// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"shop-goframe-micro-service-refacotor/app/gateway-h5/api/user"
	consignee_info "shop-goframe-micro-service-refacotor/app/user/api/consignee_info/v1"
	user_info "shop-goframe-micro-service-refacotor/app/user/api/user_info/v1"
	v1 "shop-goframe-micro-service-refacotor/utility/middleware"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	ConsigneeInfoClient consignee_info.ConsigneeInfoClient
	UserInfoClient      user_info.UserInfoClient
}

func NewV1() user.IUserV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("user", grpcx.Client.ChainUnary(
		v1.GrpcClientTimeout,
	))
	return &ControllerV1{
		UserInfoClient:      user_info.NewUserInfoClient(conn),
		ConsigneeInfoClient: consignee_info.NewConsigneeInfoClient(conn),
	}
}
