// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"shop-goframe-micro-service-refacotor/app/gateway-resource/internal/dao/internal"
)

// goodsImagesDao is the data access object for the table goods_images.
// You can define custom methods on it to extend its functionality as needed.
type goodsImagesDao struct {
	*internal.GoodsImagesDao
}

var (
	// GoodsImages is a globally accessible object for table goods_images operations.
	GoodsImages = goodsImagesDao{internal.NewGoodsImagesDao()}
)

// Add your custom methods and functionality below.
