// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	admin_info "shop-goframe-micro-service-refacotor/app/admin/api/admin_info/v1"
	"shop-goframe-micro-service-refacotor/app/gateway-admin/api/admin"
	"shop-goframe-micro-service-refacotor/utility/middleware"

	"github.com/gogf/gf/contrib/rpc/grpcx/v2"
)

type ControllerV1 struct {
	AdminInfoClient admin_info.AdminInfoClient
}

func NewV1() admin.IAdminV1 {
	var conn = grpcx.Client.MustNewGrpcClientConn("admin", grpcx.Client.ChainUnary(
		middleware.GrpcClientTimeout,
	))
	return &ControllerV1{
		AdminInfoClient: admin_info.NewAdminInfoClient(conn),
	}
}
